// MCP tool schemas (the `tools/list` payload) — pure static data, extracted from bridge.mjs to keep the
// orchestrator focused on behaviour. Edit a tool's contract here; the handler logic stays in bridge.mjs's
// CallTool switch. Keep the two in sync (a tool listed here must have a `case` there, and vice-versa).
export const TOOLS = [
  { name: 'my_identity', description: 'This bridge identity: session id, friendly name, mesh role, client info, local sub-peers.',
    inputSchema: { type: 'object', properties: {} } },
  { name: 'set_name', description: 'Set this session\'s friendly name on the mesh roster (e.g. "Scout"). NOTE: in a shared (Cowork) bridge this renames the PROCESS node — conversations should use register_self instead.',
    inputSchema: { type: 'object', properties: { name: { type: 'string' } }, required: ['name'] } },
  { name: 'register_self', description: 'Register THIS conversation (or subagent) as a sub-peer with its own identity and private inbox on a shared bridge. Invent a secret and keep it; same (name, secret) re-attaches after idle/expiry. Returns peer_id + queue_epoch (epoch change ⇒ reset your cursor). RESYNC: the response also returns `topics` (the owned + subscribed topics you currently hold, rehydrated from durable state — so a reconnecting/compacted session relearns what it is responsible for without re-claiming/re-subscribing), `access` (the projects you may reach), and an `inbox` hint (unread parked mail waiting). The bridge is the source of truth for your state across a restart.',
    inputSchema: { type: 'object', properties: {
      name: { type: 'string', description: 'friendly name, e.g. "Scout" or "scout/worker-1"' },
      secret: { type: 'string', description: 'self-invented bearer secret; only its hash is stored' },
      parent: { type: 'string', description: 'parent sub-peer handle (for subagents): full id, handle suffix, or unique name' },
      client: { type: 'string', description: 'your client kind, e.g. "claude-code" or "cowork" — code clients default to push (streaming) delivery' },
      project: { type: 'string', description: 'the project this conversation is for (classifies the session; inherited from parent if omitted)' },
      user: { type: 'string', description: 'IGNORED — the human is taken from the OS-authenticated login, not session-declared (prevents fabrication/misalignment).' },
      mode: { type: 'string', description: 'optional override: push | poll' },
      ttl_minutes: { type: 'number', description: 'idle liveness TTL; default 720, or 60 when parent is set' } }, required: ['name', 'secret'] } },
  { name: 'deregister', description: 'Remove a sub-peer (subagents: call before returning). Children are removed too; unread messages dead-letter to the parent (or the process inbox).',
    inputSchema: { type: 'object', properties: {
      peer_id: { type: 'string' }, secret: { type: 'string' } }, required: ['peer_id', 'secret'] } },
  { name: 'list_sessions', description: 'List AI sessions (with their sub-peers) and page leaves currently on the mesh.',
    inputSchema: { type: 'object', properties: {} } },
  { name: 'claim_topic', description: 'Claim ownership of (responsibility for) a CONCRETE topic (no wildcards — owning a subtree is unsendable). Topics are /-separated paths (e.g. "bridge/admin", "retail/contact-energy"). exclusive:true = ONE owner mesh-wide; a claim overlapping a held exclusive topic returns code "held" — negotiate via verb request_responsibility (grant/refuse/ask-operator), never seize. With persistence on, a claim is DURABLE by default (persistent:false opts out) and survives a restart. While the owner is offline, directed sends park for its return; set announce_offline to have senders told it is offline (else parked silently). Taking over your OWN offline (dormant) topic needs presence confirmation (authorizer/Windows Hello); a DIFFERENT user may take over only after a grace window and only if allowed. Re-claiming your own topic updates it. Owners are auto-subscribed. Sub-peers pass as + secret.',
    inputSchema: { type: 'object', properties: {
      topic: { type: 'string', description: 'concrete topic path (no wildcards)' },
      description: { type: 'string', description: 'one line on what the responsibility covers' },
      exclusive: { type: 'boolean', description: 'true = single owner mesh-wide (default false)' },
      icon: { type: 'string', description: 'optional short markdown icon (e.g. an emoji) shown wherever the topic renders' },
      persistent: { type: 'boolean', description: 'durable claim — survives a restart (default true when persistence is on; set false for an ephemeral claim)' },
      announce_offline: { type: 'boolean', description: 'when you are offline, tell senders their message was parked because you are away (default false = parked silently)' },
      grace_minutes: { type: 'number', description: 'how long after you go offline before a DIFFERENT user may take this topic over (default: realm config)' },
      allow_other_user: { type: 'boolean', description: 'may a different user take this responsibility over (after grace)? default: realm config' },
      keep_alive: { type: 'boolean', description: 'mark this topic to SURVIVE HANDOFFS: if released it stays alive (ownerless) so directed sends PARK against it until reclaimed, instead of bouncing no-owner (default false). Abandoned ownerless topics expire after a safety TTL.' },
      force: { type: 'boolean', description: 'RESERVED: operator-authorised immediate takeover — returns unsupported for now' },
      as: { type: 'string', description: 'your registered sub-peer handle (id, suffix, or name)' },
      secret: { type: 'string', description: 'the secret used at register_self' } }, required: ['topic'] } },
  { name: 'release_topic', description: 'Give up ownership of a topic you hold. By default the topic is gone (directed sends then bounce no-owner). Pass keep_alive:true (or claim it keep_alive) to KEEP IT ALIVE ownerless during a handoff: directed sends PARK and are delivered to the next session that claims it. Sub-peers pass as + secret.',
    inputSchema: { type: 'object', properties: {
      topic: { type: 'string' },
      keep_alive: { type: 'boolean', description: 'keep the topic alive (ownerless) after release so directed sends park until someone reclaims it (default = the claim\'s keep_alive setting; explicit value wins)' },
      as: { type: 'string', description: 'your registered sub-peer handle (id, suffix, or name)' },
      secret: { type: 'string', description: 'the secret used at register_self' } }, required: ['topic'] } },
  { name: 'subscribe', description: 'Subscribe to a topic pattern — open to everyone on any topic (exclusivity is about accountability, never watching). Wildcards: "+" one level, "#" subtree (e.g. "retail/#"). Publishes to matching topics land in your inbox. Sub-peers pass as + secret.',
    inputSchema: { type: 'object', properties: {
      pattern: { type: 'string', description: 'topic path or wildcard pattern' },
      as: { type: 'string', description: 'your registered sub-peer handle (id, suffix, or name)' },
      secret: { type: 'string', description: 'the secret used at register_self' } }, required: ['pattern'] } },
  { name: 'unsubscribe', description: 'Remove a subscription. Sub-peers pass as + secret.',
    inputSchema: { type: 'object', properties: {
      pattern: { type: 'string' },
      as: { type: 'string', description: 'your registered sub-peer handle (id, suffix, or name)' },
      secret: { type: 'string', description: 'the secret used at register_self' } }, required: ['pattern'] } },
  { name: 'set_behavior', description: 'Register a short REMINDER of how YOU want to behave when a message arrives that matches a scope. The bridge attaches the matching reminder(s) to each delivered message (in the channel meta and in inbox items) as reminders:[{scope,match,behavior}] — a message can match several scopes, so you may get several, ordered most-specific first (topic > subscription > project > host > all). Durable + per-identity (rehydrated on register_self). Re-registering the same scope+match replaces it. Topic-scoped reminders ride along with a kept-alive topic on handoff (the next claimant inherits them). The bridge may also attach an operator DEFAULT reminder from config (tagged default:true) — your own reminder for the same scope+match overrides it (see default_behaviors in the register_self response). Sub-peers pass as + secret.',
    inputSchema: { type: 'object', properties: {
      scope: { type: 'string', enum: ['topic', 'host', 'project', 'subscription', 'all'], description: 'topic = a topic you OWN; host = messages from a host; project = messages from a project; subscription = messages matching one of your subscription patterns; all = every incoming message' },
      match: { type: 'string', description: 'the topic / host / project / subscription-pattern this applies to (omit for scope=all)' },
      behavior: { type: 'string', description: 'the reminder prompt (short; max 280 chars) returned to you when a matching message arrives' },
      as: { type: 'string', description: 'your registered sub-peer handle (id, suffix, or name)' },
      secret: { type: 'string', description: 'the secret used at register_self' } }, required: ['scope', 'behavior'] } },
  { name: 'list_behaviors', description: 'List the behaviour reminders you have registered. Sub-peers pass as + secret.',
    inputSchema: { type: 'object', properties: {
      as: { type: 'string', description: 'your registered sub-peer handle (id, suffix, or name)' },
      secret: { type: 'string', description: 'the secret used at register_self' } } } },
  { name: 'clear_behavior', description: 'Remove a behaviour reminder (scope + match), or ALL of them if scope is omitted. Sub-peers pass as + secret.',
    inputSchema: { type: 'object', properties: {
      scope: { type: 'string', enum: ['topic', 'host', 'project', 'subscription', 'all'], description: 'the scope to clear; omit to clear every reminder' },
      match: { type: 'string', description: 'the match to clear (for scope other than all)' },
      as: { type: 'string', description: 'your registered sub-peer handle (id, suffix, or name)' },
      secret: { type: 'string', description: 'the secret used at register_self' } } } },
  { name: 'publish', description: 'Publish an event to a concrete topic: delivered to ALL subscribers (wildcard matches included; owners are auto-subscribed). Nobody is obliged to act — for directed work send to "topic:<topic>" instead. Zero subscribers is ok. subject is REQUIRED: short public one-line description (NOT encrypted — no private info).',
    inputSchema: { type: 'object', properties: {
      topic: { type: 'string', description: 'concrete topic path (no wildcards)' },
      subject: { type: 'string', description: 'short PUBLIC one-line description of the event' },
      message: { type: 'string', description: 'the message body (encrypted in transit)' },
      verb: { type: 'string', description: 'advisory verb, default "message"' },
      retain: { type: 'boolean', description: 'keep this as the topic\'s retained "last value" (persistence on); a new/returning subscriber gets it immediately on subscribe. Concrete topics only.' },
      as: { type: 'string', description: 'your registered sub-peer handle (id, suffix, or name)' },
      secret: { type: 'string', description: 'the secret used at register_self' } }, required: ['topic', 'subject', 'message'] } },
  { name: 'send_to_peer', description: 'Send a directed message: target = id from list_sessions, a unique friendly name, or "topic:<topic>" to message the topic\'s OWNER(S) only (the prefix is required; subscribers do not see sends). With persistence on, a send to a name (or topic owner) that is OFFLINE but has a durable registration/claim PARKS and is delivered when it returns; a name that was never registered still errors unknown-target. subject is REQUIRED: short public one-line description (NOT encrypted — no private info; the body is encrypted). Registered sub-peers must pass as + secret.',
    inputSchema: { type: 'object', properties: {
      target: { type: 'string', description: 'session/sub-peer id, unique friendly name, or topic:<topic>. A bare topic resolves to an owner in YOUR project; if none, it resolves cross-project to a grant-reachable owner in another project (auto-routed when exactly one — else code cross-project-no-grant / cross-project-ambiguous). Use topic:@<project>/<topic> to target a specific project explicitly.' },
      subject: { type: 'string', description: 'short PUBLIC one-line description of the action' },
      message: { type: 'string', description: 'the message body (encrypted in transit)' },
      verb: { type: 'string', description: 'advisory verb, default "message"' },
      reply_to: { type: 'string', description: 'envelope_id being replied to' },
      park: { type: 'boolean', description: 'RESERVED (offline delivery): park for a known-but-offline agent — returns unsupported for now' },
      as: { type: 'string', description: 'your registered sub-peer handle (id, suffix, or name)' },
      secret: { type: 'string', description: 'the secret used at register_self' } }, required: ['target', 'subject', 'message'] } },
  { name: 'allow_project', description: 'Open YOUR project to inbound messages from another project (receiver-controlled consent). The caller\'s project grants `project` permission to initiate to it. mode "send" (one-way) or "bidirectional". As the operator you may set ttl_minutes to expire the grant (and may shorten what a requester asked for); omit for forever. Approving a pending request_project_access auto-notifies the requester (project_access_granted) with the permitted TTL. Durable across restart when persistence is on; for a permanent static edge add it to config.json projects.allow. Sub-peers pass as + secret.',
    inputSchema: { type: 'object', properties: {
      project: { type: 'string', description: 'the foreign project being granted access to yours' },
      mode: { type: 'string', description: 'send (default) | bidirectional' },
      ttl_minutes: { type: ['number', 'string'], description: 'grant lifetime: minutes (number) or a duration like "24h"/"7d"; omit / 0 / "forever" = no expiry. May only shorten a requester\'s asked-for TTL.' },
      as: { type: 'string' }, secret: { type: 'string' } }, required: ['project'] } },
  { name: 'revoke_project', description: 'Revoke a runtime grant created with allow_project (drops the durable edge too; does not affect static config edges).',
    inputSchema: { type: 'object', properties: {
      project: { type: 'string' }, as: { type: 'string' }, secret: { type: 'string' } }, required: ['project'] } },
  { name: 'request_project_access', description: 'Ask another project for permission to reach it. The bridge delivers a project_access_request to that project\'s sessions (by name, even though you cannot see them); an operator there approves by calling allow_project. You will then receive a project_access_granted message echoing your request_id + the permitted TTL. Returns a request_id.',
    inputSchema: { type: 'object', properties: {
      to: { type: 'string', description: 'the project you want to reach' },
      reason: { type: 'string', description: 'why (shown to the target operator)' },
      ttl_minutes: { type: ['number', 'string'], description: 'how long you want the access for: minutes (number) or a duration like "24h"/"7d"; omit / "forever" = indefinite. The operator may grant a shorter TTL.' },
      as: { type: 'string' }, secret: { type: 'string' } }, required: ['to'] } },
  { name: 'set_wake', description: 'RESERVED (wake feature): arm a wake listener for an idle session, with filters (sends always; publishes per pattern). Returns unsupported for now.',
    inputSchema: { type: 'object', properties: {
      for: { type: 'string' }, secret: { type: 'string' },
      mode: { type: 'string', description: 'off | exit-on-message' },
      filter: { type: 'object', description: '{sends?: bool, publishes?: pattern[] | false}' } } } },
  { name: 'inbox', description: 'Poll received messages. Registered sub-peers pass for + secret (+ cursor from the previous call); response carries queue_epoch — if it changed, reset cursor to 0. Without for: the shared process inbox.',
    inputSchema: { type: 'object', properties: {
      cursor: { type: 'number' },
      for: { type: 'string', description: 'your registered sub-peer handle' },
      secret: { type: 'string' } } } },
  { name: 'recover_secret', description: 'RECOVER a lost inbox secret via the user\'s PRESENCE (Windows Hello), for when a session forgot its secret (e.g. after a compact). No secret is required — the bridge sealed it to the user\'s TPM at registration, so only the real human at their own machine can unseal it. On approval it returns the original secret; re-register with name + that secret to reattach and get your topics + parked mail back. Requires the vault facet (returns unsupported otherwise).',
    inputSchema: { type: 'object', properties: {
      name: { type: 'string', description: 'the session name whose secret to recover' },
      project: { type: 'string', description: 'optional — disambiguate if the name exists in more than one project' } }, required: ['name'] } },
]
