// Fast UNIT tests for #88 (v2.0) build step 2a — the id-keyed model's STRUCTURE and RESOLUTION (lib/activity2.js;
// docs/spec-88.md §1 – §3, §5.1, §8 step 2): resolution + idempotency, label uniqueness (auto-rename on create incl. the
// 60-code-point cut, a retry not making "(3)", --label = asked raising no `exists`), the refusals (duplicate key,
// duplicate-label on rename / move, depth hard + soft, cross-session, unknown-agent), merge (incl. clashes) / unmerge,
// aliases, ghosts + resurrection, transient vanish with and without a grace period (Q44), the running-agent move, and
// --move-to (§3.8, Q45's bare-name refusal). Pure: no bridge, no sockets; time is passed in.
import { testOnly } from '../helpers/check.mjs'
import * as M from '../../lib/activity2.js'
import { mintId, DEPTH2 } from '../../lib/activity.js'
let pass = 0, fail = 0
const check = (n, c, x = '') => { if (!testOnly(n)) return; let ok = false; try { ok = typeof c === 'function' ? !!c() : !!c } catch (e) { x = `threw: ${e && e.message} ${x}` } ok ? (pass++, console.log('PASS', n)) : (fail++, console.log('FAIL', n, x)) }
const J = JSON.stringify
async function section(fn) { try { await fn() } catch (e) { fail++; console.log('FAIL section crashed:', (e && e.stack) || e) } }
const BRIDGET = { session: 'Bridget', project: 'AIMB', user: 'robin' }
const T0 = 1790984000000
// a fresh model + a call helper with a ticking clock
function world(origin = 'ROBIN-Z790') {
  const st = M.createModel({ origin })
  let now = T0
  const call = (x, ident = BRIDGET, o) => M.applyCall(st, ident, x, now++, o)
  const sess = (ident = BRIDGET) => M.getSession2(st, ident)
  const tick = ms => { now += ms; return now }
  const at = () => now
  const tree = (ident = BRIDGET) => J(M.treeOf(sess(ident)), (k, v) => (k === 'id' || k === 'key' ? undefined : v))
  const node = (path, ident = BRIDGET) => { const n = M.findPath(sess(ident), path); return n ? M.nodeView(sess(ident), n) : null }
  return { st, call, sess, tick, at, tree, node }
}
// a deterministic snapshot of a session's state (for "nothing changed" checks)
const snap = s => J({ n: [...s.nodes.values()].map(n => [n.id, n.parent, n.label, n.merged_into, n.transient, n.rank, n.empty_since]).sort(), k: [...s.kids].map(([k, v]) => [k, [...v].sort()]).sort(),
  l: [...s.labels].sort(), sc: [...s.scope].sort(), a: [...s.aliases.keys()].sort(), g: [...s.ghosts.keys()].sort() })
const codes = r => (r.warnings || []).map(w => w.code)
const ops = r => (r.records || []).map(x => x.op)

// ================================================================= resolution + idempotency (§3)
await section(() => {
  const w = world()
  const a = w.call({ key: 'docs', label: 'Write the docs' })
  check('resolve: --key creates a context in the session scope (id = mintId(session, "", key))', a.ok && a.created && a.node.kind === 'context' && a.node.id === mintId({ ...BRIDGET, host: 'ROBIN-Z790' }, '', 'docs') && a.node.path === 'Write the docs' && a.node.scope === '', J(a))
  check('resolve: Bridget\'s :spec-88 id matches the spec vector (uytyq4e6wsmtqsfq)', w.call({ agent: 'spec-88', label: 'Spec pass' }).node.id === 'uytyq4e6wsmtqsfq')
  const r1 = a.records[0]
  check('records: create = { v:6, kind:"node", op:"create", n, c, key, nk, label, p, rank:null, run:true, …ident }', r1.v === 6 && r1.kind === 'node' && r1.op === 'create' && r1.n === a.node.id && r1.c === w.sess().rootId && r1.key === 'docs' && r1.nk === 'context' && r1.label === 'Write the docs' && r1.p === w.sess().rootId && r1.rank === null && r1.run === true && r1.session === 'Bridget' && r1.host === 'ROBIN-Z790' && r1.origin === 'ROBIN-Z790' && r1.s0 === T0, J(r1))
  const b = w.call({ key: 'docs', label: 'Write the docs' })
  check('idempotent: the same create again reaches the same node, writes nothing, no warning', b.ok && !b.created && b.node.id === a.node.id && b.records.length === 0 && b.warnings.length === 0)
  const c = w.call({ key: 'DOCS' })
  check('idempotent: keys compare case-insensitively (--key DOCS finds docs)', c.ok && c.node.id === a.node.id && !c.created)
  w.call({ key: 'later', label: 'Later' })
  const d = w.call({ key: 'docs', label: 'Other', under: 'later' })
  check('exists: --under / --label on an existing node are IGNORED with warning exists (H2)', d.ok && codes(d).includes('exists') && J(d.warnings[0].ignored) === J(['label', 'under']) && d.node.path === 'Write the docs' && d.records.length === 0, J(d.warnings))
  check('resolve: --key without --label on a new key → label-required (Q31)', w.call({ key: 'nolabel' }).code === 'label-required')
  check('resolve: --id names a node exactly', w.call({ id: a.node.id }).node.key === 'docs')
  check('resolve: --id of nothing → unknown-node', w.call({ id: 'aaaaaaaaaaaaaaaa' }).code === 'unknown-node')
  check('resolve: no key / id / path / agent → the session root', w.call({}).node.kind === 'session' && w.call({}).node.path === '')
  check('resolve: --key with --path → bad-address', w.call({ key: 'docs', path: 'x' }).code === 'bad-address')
  // paths
  const p = w.call({ path: 'Next release/#88/Docs' })
  check('path: creates the missing tail as contexts (intermediates implicit), key = slug (Docs-2: the session already holds docs), creator = the owner (the session)', p.ok && p.created && J(ops(p)) === J(['create', 'create', 'create']) && p.node.key === 'Docs-2' && p.node.scope === '' && p.records[0].key === 'Next-release' && p.records[1].key === '88', J(p.records.map(x => x.key)))
  check('path: a second identical path reports into the first (never collides with itself)', w.call({ path: 'next release/#88/docs' }).node.id === p.node.id)
  const q = w.call({ path: 'Elsewhere/Docs' })
  check('path: the same label elsewhere gets key Docs-3 in the same scope (slug clash, §1.1)', q.ok && q.node.key === 'Docs-3', q.node && q.node.key)
  check('path: the path-created node is reachable by its key', w.call({ key: 'Docs-2' }).node.id === p.node.id)
  check('path: an @ segment is refused legacy-form', w.call({ path: '@Next release/@Docs' }).code === 'legacy-form')
  // agents
  const ag = w.call({ agent: 'spec-88', path: 'notes' })
  check('agent: a path walks from the --agent node; its contexts get the AGENT as creator (spec-88:notes)', ag.ok && ag.node.path === 'Spec pass/notes' && ag.node.scope === 'spec-88' && ag.node.id === mintId({ ...BRIDGET, host: 'ROBIN-Z790' }, 'spec-88', 'notes'))
  const sub = w.call({ agent: 'spec-88/research', label: 'Research' })
  check('agent: a sub-agent is created under its creator (chain spec-88/research)', sub.ok && sub.created && sub.node.path === 'Spec pass/Research' && sub.node.scope === 'spec-88' && sub.node.kind === 'agent')
  const k2 = w.call({ agent: 'spec-88', key: 'docs', label: 'Agent docs' })
  check('scope: an agent\'s --key docs never lands in the session\'s docs (keys are per creator)', k2.ok && k2.created && k2.node.id !== a.node.id && k2.node.scope === 'spec-88' && k2.node.path === 'Spec pass/Agent docs')
  const u = w.call({ agent: 'spec-88/research', key: 'n1', label: 'N1', under: 'docs' })
  check('ref: a bare key looks in your scope, then your creator\'s, up to the session (lexical): research --under docs finds spec-88:docs', u.ok && u.node.path === 'Spec pass/Agent docs/N1', u.node && u.node.path)
  check('ref: chain:key names exactly that scope (:docs = the session\'s)', w.call({ key: 'n2', label: 'N2', under: ':docs' }).node.path === 'Write the docs/N2')
  check('ref: a path reference resolves without creating (unknown-node)', w.call({ key: 'n3', label: 'N3', under: 'No such/place' }).code === 'unknown-node' && !w.node('No such'))
  check('ref: an unknown key reference → unknown-node, and the create is not made', w.call({ key: 'n4', label: 'N4', under: 'nokey' }).code === 'unknown-node' && w.call({ key: 'n4' }).code === 'label-required')
})

// ================================================================= label uniqueness (§1.6)
await section(() => {
  const w = world()
  w.call({ key: 'a', label: 'Notes' })
  const b = w.call({ key: 'b', label: 'notes' })
  check('labels: a clashing CREATE is auto-renamed "notes (2)", the result says what it got (warning relabelled)', b.ok && b.node.label === 'notes (2)' && codes(b).includes('relabelled'), J(b.warnings))
  const rw = b.warnings.find(x => x.code === 'relabelled')
  check('labels: relabelled = { asked, got, sibling:{label, key, id} }; the create record keeps asked', rw.asked === 'notes' && rw.got === 'notes (2)' && rw.sibling.key === 'a' && rw.sibling.label === 'Notes' && b.records[0].asked === 'notes' && b.records[0].label === 'notes (2)')
  const c = w.call({ key: 'c', label: 'NOTES' })
  check('labels: the next clash gets "(3)" (the suffix counts in the comparison)', c.node.label === 'NOTES (3)')
  const retry = w.call({ key: 'b', label: 'notes' })
  check('labels: a RETRY of the clashing create reaches the same node — no "(3)", no new record', retry.ok && !retry.created && retry.node.id === b.node.id && retry.node.label === 'notes (2)' && retry.records.length === 0)
  check('labels: --label equal to the create\'s asked label raises NO exists (H19)', retry.warnings.length === 0, J(retry.warnings))
  check('labels: a different --label on it still warns exists', codes(w.call({ key: 'b', label: 'Other' })).includes('exists'))
  const long = 'x'.repeat(60)
  w.call({ key: 'l1', label: long })
  const l2 = w.call({ key: 'l2', label: long })
  check('labels: a 60-code-point label is cut BEFORE the suffix → 56 x + " (2)" = 60 code points', l2.node.label === 'x'.repeat(56) + ' (2)' && [...l2.node.label].length === 60, l2.node.label)
  const astral = '\u{1D49C}'.repeat(60)
  w.call({ key: 'l3', label: astral })
  const l4 = w.call({ key: 'l4', label: astral })
  check('labels: the cut counts CODE POINTS (astral letters)', [...l4.node.label].length === 60 && l4.node.label.endsWith(' (2)'))
  check('labels: NFC + case-insensitive (Café = CAFÉ written NFD)', (w.call({ key: 'cf1', label: 'Café' }), w.call({ key: 'cf2', label: 'CAFÉ' }).node.label === 'CAFÉ (2)'))
  // agents and contexts share the rule
  const ag = w.call({ agent: 'bot', label: 'Notes' })
  check('labels: agents share the rule (an agent labelled like a context sibling → "Notes (4)")', ag.ok && ag.node.label === 'Notes (4)', ag.node && ag.node.label)
  // a path never clashes with itself: it matches by label
  check('labels: a path segment matching a label reports into that node', w.call({ path: 'notes' }).node.key === 'a')
  check('labels: a path segment matches an AGENT by its key when no label matches (bot → "Notes (4)")', w.call({ path: 'bot' }).node.kind === 'agent')
  // freed by removal
  const s = w.sess(), aId = b.node.id
  M.removeById(w.st, s, aId, 'dismiss', w.tick(1))
  check('labels: a label freed by a removal can be used again (ghosts are not counted)', w.call({ key: 'b2', label: 'notes (2)' }).node.label === 'notes (2)')
})

// ================================================================= refusals: duplicate key / label, depth, cross-session, unknown-agent
await section(() => {
  const w = world()
  w.call({ key: 'a', label: 'A' }); w.call({ key: 'b', label: 'B' })
  w.call({ key: 'a1', label: 'Notes', under: 'a' }); w.call({ key: 'b1', label: 'notes', under: 'b' })
  w.call({ agent: 'bot', label: 'Bot' })
  // duplicate key
  const before = J(M.treeOf(w.sess()))
  check('dup key: a create with an existing key never makes a second node (reaches it: idempotent)', w.call({ key: 'a', label: 'Another A', under: 'b' }).node.path === 'A' && J(M.treeOf(w.sess())) === before)
  check('dup key: --agent naming a CONTEXT key → not-an-agent (agents and contexts share one namespace)', w.call({ agent: 'a', label: 'X' }).code === 'not-an-agent')
  check('dup key: --key naming the agent finds the AGENT (one namespace)', w.call({ key: 'bot' }).node.kind === 'agent')
  const s = w.sess(), ident = { ...BRIDGET, host: 'ROBIN-Z790' }
  // plant a node holding the id that a new key would mint, under another key (a forced collision)
  const victim = mintId(ident, '', 'fresh'), fake = { ...s.nodes.get(s.scope.get(s.rootId + '\na')), id: victim, key: 'zzz' }
  s.nodes.set(victim, fake)
  const col = w.call({ key: 'fresh', label: 'Fresh' })
  check('dup key: a mint hitting ANOTHER node\'s id → id-collision, nothing merged', col.code === 'id-collision', J(col))
  s.nodes.delete(victim)
  // duplicate label on rename / move
  const snap0 = snap(s)
  const rn = w.call({ key: 'b', rename: 'a' })
  check('dup label: --rename onto a sibling\'s label → duplicate-label naming the sibling + the suggestion', rn.code === 'duplicate-label' && rn.sibling.key === 'a' && rn.suggestion === 'a (2)', J(rn))
  const mv = w.call({ key: 'a1', move: 'b' })
  check('dup label: --move next to a same-label sibling → duplicate-label (nothing written)', mv.code === 'duplicate-label' && mv.sibling.key === 'b1' && mv.suggestion === 'Notes (2)' && snap(s) === snap0, J(mv))
  const mr = w.call({ key: 'a1', move: 'b', rename: 'Notes (A)' })
  check('dup label: --move + --rename is ONE checked change: both records', mr.ok && J(ops(mr)) === J(['move', 'label']) && mr.node.path === 'B/Notes (A)', J(mr))
  check('dup label: --move + --rename onto a clash → refused, NEITHER record', (() => { w.call({ key: 'c1', label: 'C1', under: 'a' }); const r = w.call({ key: 'c1', move: 'b', rename: 'notes' }); return r.code === 'duplicate-label' && w.call({ key: 'c1' }).node.path === 'A/C1' })())
  check('dup label: a rename that only changes case is allowed (no clash with itself)', w.call({ key: 'b1', rename: 'NOTES' }).ok && w.call({ key: 'b1' }).node.label === 'NOTES')
  check('dup label: a rename to the same label is a no-op (no record)', w.call({ key: 'b1', rename: 'NOTES' }).records.length === 0)
  // unknown / not agents
  check('unknown-agent: a missing earlier chain step', w.call({ agent: 'nobody/sub', label: 'S' }).code === 'unknown-agent')
  check('unknown-agent: a missing agent on a call aimed at another node (never created as a side effect)', w.call({ agent: 'ghostly', key: 'k', label: 'K' }).code === 'unknown-agent' && w.call({ agent: 'ghostly', path: 'x' }).code === 'unknown-agent')
  check('unknown-agent: the message names the fix (--guide agent)', /--agent ghostly --label "…" --guide agent/.test(w.call({ agent: 'ghostly', key: 'k', label: 'K' }).what))
  check('label-required: creating an agent needs --label (Q40)', w.call({ agent: 'newbie' }).code === 'label-required')
  check('agent: --transient on an agent create → bad-input (contexts only)', w.call({ agent: 'tbot', label: 'T', transient: true }).code === 'bad-input')
  // cross-session
  const other = { ...BRIDGET, session: 'Other' }
  const o = w.call({ key: 'there', label: 'There' }, other)
  const cs = w.call({ key: 'a', move_id: o.node.id })
  check('cross-session: --move_id to another session\'s node → cross-session', cs.code === 'cross-session', J(cs))
  check('cross-session: a running agent can\'t move to another session either (Q15)', w.call({ key: 'bot', move_id: o.node.id }).code === 'cross-session')
  check('cross-session: merge_id across sessions → cross-session', w.call({ key: 'a', merge_id: o.node.id }).code === 'cross-session')
  check('cross-session: the sessions are separate trees (ids hash the session)', o.node.id !== w.call({ key: 'there', label: 'There' }).node.id)
  // other move refusals
  check('move: the session root cannot move', w.call({ move: 'a' }).code === 'bad-move')
  check('move: never under itself or below', w.call({ key: 'a', move: 'a' }).code === 'bad-move' && w.call({ key: 'a', move: 'c1' }).code === 'bad-move')
  check('move: one destination per call (--move with --move-to) → bad-input', w.call({ key: 'a', move: 'b', move_to: '../X' }).code === 'bad-input')
  check('move: to where it already is → a no-op (no record)', w.call({ key: 'c1', move: 'a' }).records.length === 0)
})

// ================================================================= depth (Q11b): hard 32, warning past 20
await section(() => {
  const w = world()
  const chain = n => Array.from({ length: n }, (_, i) => 'L' + (i + 1)).join('/')
  const d20 = w.call({ path: chain(20) })
  check('depth: 20 deep → no warning', d20.ok && !codes(d20).includes('deep-tree'))
  const d21 = w.call({ path: chain(21) })
  check('depth: 21 deep → succeeds with warning deep-tree {depth:21}', d21.ok && d21.warnings.some(x => x.code === 'deep-tree' && x.depth === 21), J(d21.warnings))
  const d32 = w.call({ path: chain(32) })
  check('depth: 32 deep → succeeds (deep-tree 32)', d32.ok && d32.warnings.some(x => x.code === 'deep-tree' && x.depth === 32))
  const s = w.sess(), snap0 = snap(s)
  const d33 = w.call({ key: 'too', label: 'Too deep', under: chain(32) })
  check('depth: a create at 33 → refused depth, naming the node and the depth; nothing written', d33.code === 'depth' && d33.depth === 33 && d33.node.label === 'Too deep' && snap(s) === snap0, J(d33))
  // a move counts the whole subtree
  w.call({ path: 'Sub/S1/S2/S3' })                      // a subtree 3 below Sub
  const mv = w.call({ path: 'Sub', move: chain(29) })   // Sub would land at 30, S3 at 33
  check('depth: a move counts the WHOLE subtree — refused, naming the deepest node (S3 at 33)', mv.code === 'depth' && mv.depth === 33 && mv.node.label === 'S3' && snap(s) !== '' && w.node('Sub/S1/S2/S3') !== null, J(mv))
  const ok = w.call({ path: 'Sub', move: chain(28) })
  check('depth: the same subtree one level higher fits (S3 at 32) with deep-tree 32', ok.ok && ok.warnings.some(x => x.code === 'deep-tree' && x.depth === 32), J(ok.warnings))
  w.call({ key: 'top', label: 'Top' })
  const mt = w.call({ key: 'top', move_to: '/' + chain(32) })
  check('depth: --move-to into a 32-deep node → depth (the moved node would be 33)', mt.code === 'depth')
  const mt2 = w.call({ key: 'top', move_to: '/' + chain(31) + '/New bucket' })
  check('depth: --move-to whose CREATED bucket fits (32) but the node would not (33) → depth, the bucket not created either', mt2.code === 'depth' && !w.node(chain(31) + '/New bucket'))
  check('depth: the limits are DEPTH2 = { max:32, warn:20 }', DEPTH2.max === 32 && DEPTH2.warn === 20 && M.LIMITS2.depthMax === 32)
  // the at cap + display form
  const long = Array.from({ length: 32 }, (_, i) => 'Ü'.repeat(58) + i).join('/')
  const cap = M.capAt(long)
  check('at cap: a long path is capped at 1024 UTF-8 bytes, cut in the MIDDLE with …', Buffer.byteLength(cap) <= 1024 && cap.includes('…') && cap.startsWith('ÜÜÜ') && cap.endsWith('31') && Buffer.byteLength(cap) > 1000, Buffer.byteLength(cap))
  check('at cap: a short path is unchanged', M.capAt('a/b') === 'a/b')
  check('shortPath: Next release/…/Write the docs (first segment, …, trailing segments that fit)', M.shortPath('Next release/#88 stable node identity (v2.0)/Build step 2a/Write the docs', 40) === 'Next release/…/Write the docs', M.shortPath('Next release/#88 stable node identity (v2.0)/Build step 2a/Write the docs', 40))
  check('shortPath: a short path is unchanged; a single long label is cut in the middle', M.shortPath('a/b', 40) === 'a/b' && [...M.shortPath('x'.repeat(100), 40)].length === 40)
})

// ================================================================= merge (incl. clashes) and unmerge (§3.6)
await section(() => {
  const w = world()
  w.call({ key: 'rel', label: 'Rel' })
  w.call({ key: 'A', label: 'Stray', under: 'rel' }); w.call({ key: 'B', label: '#79 three-part progress', under: 'rel' })
  w.call({ key: 'a1', label: 'Notes', under: 'A' }); w.call({ key: 'a2', label: 'Plan', under: 'A' }); w.call({ key: 'b1', label: 'notes', under: 'B' })
  const s = w.sess(), snap0 = snap(s)
  const cl = w.call({ key: 'A', merge: 'B' })
  check('merge: a child label clash → duplicate-label listing EVERY clash with its suggestion; nothing written', cl.code === 'duplicate-label' && cl.clashes.length === 1 && cl.clashes[0].key === 'a1' && cl.clashes[0].sibling.key === 'b1' && cl.clashes[0].suggestion === 'Notes (2)' && snap(s) === snap0, J(cl))
  w.call({ key: 'a1', rename: 'Notes from A' })
  const m = w.call({ key: 'A', merge: 'B' })
  check('merge: A into B — one merge record {into, from, was, kids}, no move records', m.ok && J(ops(m)) === J(['merge']) && m.records[0].into === m.merged.into_id && m.records[0].from === s.scope.get(s.rootId + '\nrel') && m.records[0].was === 'Rel/Stray' && m.records[0].kids.length === 2, J(m.records))
  check('merge: A\'s children now sit under B (last), A is hidden', w.tree() === J({ label: 'Bridget', kids: [{ label: 'Rel', kids: [{ label: '#79 three-part progress', kids: [{ label: 'notes', kids: [] }, { label: 'Notes from A', kids: [] }, { label: 'Plan', kids: [] }] }] }] }), w.tree())
  const k = w.call({ key: 'A' })
  check('merge: --key A now targets B, warning merged', k.ok && k.node.key === 'B' && codes(k).includes('merged'))
  const p = w.call({ path: 'Rel/Stray' })
  check('merge: A\'s old path is an alias → resolves to B (alias + merged)', p.ok && !p.created && p.node.key === 'B' && codes(p).includes('alias'), J(p.warnings))
  check('merge: A\'s label is free again among Rel\'s children (a hidden merged node is not counted)', w.call({ key: 'X', label: 'Stray', under: 'rel' }).node.label === 'Stray')
  w.call({ key: 'X', rename: 'X' })
  // refusals
  w.call({ agent: 'bot', label: 'Bot', under: 'rel' })
  check('merge: A = B → bad-merge', w.call({ key: 'B', merge: 'B' }).code === 'bad-merge')
  check('merge: into its own descendant → bad-merge', w.call({ key: 'rel', merge: 'b1' }).code === 'bad-merge')
  check('merge: an agent (either side) → bad-merge', w.call({ key: 'bot', merge: 'B' }).code === 'bad-merge' && w.call({ key: 'X', merge: 'bot' }).code === 'bad-merge')
  check('merge: the session root → bad-merge', w.call({ merge: 'B' }).code === 'bad-merge')
  // unmerge
  const u = w.call({ key: 'A', unmerge: true })
  check('unmerge: A goes back under its old parent (Rel) — one unmerge record; its children stay with B', u.ok && J(ops(u)) === J(['unmerge']) && u.node.path === 'Rel/Stray' && w.node('Rel/#79 three-part progress/Plan') !== null, J(u))
  check('unmerge: --key A targets A itself again (no redirect)', w.call({ key: 'A' }).node.key === 'A' && !codes(w.call({ key: 'A' })).includes('merged'))
  check('unmerge: of a node that is not merged → bad-unmerge', w.call({ key: 'A', unmerge: true }).code === 'bad-unmerge')
  w.call({ key: 'A', merge: 'B' })
  w.call({ key: 'Y', label: 'Stray', under: 'rel' })
  const uc = w.call({ key: 'A', unmerge: true })
  check('unmerge: the old parent gained a child with A\'s label → duplicate-label', uc.code === 'duplicate-label' && uc.sibling.key === 'Y')
  const ul = w.call({ key: 'A', unmerge: true, label: 'Stray (old)' })
  check('unmerge: --label names A anew (unmerge + label records)', ul.ok && J(ops(ul)) === J(['unmerge', 'label']) && ul.node.path === 'Rel/Stray (old)', J(ul))
  // a merged node moves with its target
  w.call({ key: 'A', merge: 'B' })
  w.call({ key: 'B', move: ':Y' })
  check('merge: a hidden merged node travels with B (B moved): still resolves to B', w.call({ key: 'A' }).node.path === 'Rel/Stray/#79 three-part progress')
})

// ================================================================= aliases (§3.3)
await section(() => {
  const w = world()
  w.call({ path: 'Next release/#88/Docs' })
  w.call({ path: 'Later' })
  const mv = w.call({ path: 'Next release/#88/Docs', move: 'Later' })
  check('alias: a move writes was and makes the old path an alias', mv.ok && mv.records[0].was === 'Next release/#88/Docs' && w.sess().aliases.has('next release/#88/docs'))
  const a = w.call({ path: 'Next release/#88/Docs' })
  check('alias: the old path now reaches the MOVED node (no re-creation), warning alias names the new path', a.ok && !a.created && a.node.path === 'Later/Docs' && a.warnings.some(x => x.code === 'alias' && x.now === 'Later/Docs'), J(a))
  w.call({ path: 'Next release/#88', rename: '#88 stable ids' })
  const deeper = w.call({ path: 'Next release/#88/Spec' })
  check('alias: the longest alias PREFIX wins and the rest resolves (or is created) below it', deeper.ok && deeper.node.path === 'Next release/#88 stable ids/Spec', deeper.node && deeper.node.path)
  const live = w.call({ path: 'Next release/#88' })
  check('alias: the LIVE tree always wins — a node made at the old path is found first', live.ok && live.node.path === 'Next release/#88 stable ids')
  w.call({ key: 'n88', label: '#88', under: 'Next release' })
  check('alias: …once a live node holds the path again, it is that one', w.call({ path: 'Next release/#88' }).node.key === 'n88')
  // lifetime
  const s = w.sess()
  const count = () => s.aliases.size
  const n0 = count()
  check('alias: expireAliases keeps fresh aliases', M.expireAliases(w.st, w.at()) === 0 && count() === n0)
  check('alias: …and drops them log_retention_days after their last use', M.expireAliases(w.st, w.at() + 8 * 86400000) === n0 && count() === 0)
  // ≤ 16 per node, newest kept
  w.call({ key: 'hop', label: 'Hop0' })
  for (let i = 1; i <= 20; i++) w.call({ key: 'hop', rename: 'Hop' + i })
  const mine = [...s.aliases.values()].filter(x => x.id === w.call({ key: 'hop' }).node.id)
  check('alias: ≤ 16 per node, the newest kept', mine.length === 16 && mine.some(x => x.path === 'Hop19') && !mine.some(x => x.path === 'Hop0'), mine.length)
  // dropped with the node
  M.removeById(w.st, s, w.call({ key: 'hop' }).node.id, 'dismiss', w.tick(1))
  check('alias: dropped when the node is removed', ![...s.aliases.values()].some(x => x.path.startsWith('Hop')))
  // collision: newest wins
  w.call({ key: 'p', label: 'P' }); w.call({ key: 'q', label: 'Q' })
  w.call({ key: 'p', rename: 'P2' }); w.call({ key: 'q', rename: 'P' }); w.call({ key: 'q', rename: 'Q2' })
  check('alias: two aliases with one path → the NEWEST wins', w.call({ path: 'P' }).node.key === 'q')
})

// ================================================================= ghosts and resurrection (§3.7, §5.1)
await section(() => {
  const w = world()
  w.call({ key: 'par', label: 'Parent' })
  const c = w.call({ key: 'kid', label: 'Kid', under: 'par' })
  w.call({ key: 'gk', label: 'Grandkid', under: 'kid' })
  const s = w.sess()
  const rm = M.removeById(w.st, s, c.node.id, 'dismiss', w.tick(10))
  check('ghost: a remove writes ONE record (why, was) for the subtree top', rm.ok && J(rm.records.map(r => [r.op, r.why, r.was])) === J([['remove', 'dismiss', 'Parent/Kid']]))
  check('ghost: the node and its subtree leave memory into the ghost table (last parent kept)', !s.nodes.has(c.node.id) && s.ghosts.get(c.node.id).parent === s.scope.get(s.rootId + '\npar') && s.ghosts.size === 2)
  check('ghost: its key stays held in the scope (a key names one node for good)', s.scope.has(s.rootId + '\nkid'))
  const back = w.call({ key: 'kid' })
  check('ghost: --key of a ghost → a NEW RUN of the SAME id (create run:true), back under its default place', back.ok && back.created && back.node.id === c.node.id && back.records[0].op === 'create' && back.records[0].run === true && s.nodes.get(c.node.id).runs === 2, J(back))
  check('ghost: …its ghost children stay ghosts', s.ghosts.size === 1 && [...s.ghosts.values()][0].label === 'Grandkid')
  check('ghost: a path re-using a removed node\'s name RESURRECTS it (same id, new run)', (() => { const g = w.call({ path: 'Kid/Grandkid' }); return g.ok && g.created && s.ghosts.size === 0 && g.records[0].run === true })())
  // lifetime
  const old = w.call({ key: 'old', label: 'Old', under: 'par' })
  w.call({ key: 'oldkid', label: 'Old kid', under: 'old' })
  M.removeById(w.st, s, old.node.id, 'evict', w.tick(5))
  const t1 = w.at()
  check('ghost lifetime: kept while retained', M.pruneGhosts(w.st, t1 - 1000).length === 0 && s.ghosts.size === 2)
  s.ghosts.get(s.scope.get(s.rootId + '\noldkid')).last_ts = t1 + 99999   // the grandchild has newer entries
  check('ghost lifetime: a ghost stays while a ghost BELOW it still has retained entries', M.pruneGhosts(w.st, t1 + 1).length === 0 && s.ghosts.has(old.node.id))
  const dropped = M.pruneGhosts(w.st, t1 + 100000 + 1)
  check('ghost lifetime: both leave once nothing in their subtree is retained — their keys are freed', dropped.length === 2 && !s.ghosts.size && !s.scope.has(s.rootId + '\nold'))
  check('ghost: the root cannot be removed', M.removeById(w.st, s, s.rootId, 'dismiss', w.at()).code === 'bad-remove')
})

// ================================================================= the running-agent move (Q15, §1.5)
await section(() => {
  const w = world()
  w.call({ key: 'n88', label: '#88' }); w.call({ key: 'later', label: 'Later' })
  const ag = w.call({ agent: 'spec-88', label: 'Spec pass', under: 'n88' })
  w.call({ agent: 'spec-88', key: 'docs', label: 'Docs' })
  const mv = w.call({ key: 'spec-88', move: 'later' })
  check('agent move: a running agent moves within its session (one move record)', mv.ok && J(ops(mv)) === J(['move']) && mv.node.path === 'Later/Spec pass' && mv.node.id === ag.node.id)
  const next = w.call({ agent: 'spec-88', key: 'docs' })
  check('agent move: its next report (--agent / --key) lands in the MOVED node', next.ok && next.node.path === 'Later/Spec pass/Docs' && !next.created)
  check('agent move: its new contexts go under it there', w.call({ agent: 'spec-88', path: 'Notes' }).node.path === 'Later/Spec pass/Notes')
  check('agent move: the old path is an alias for path callers', w.call({ path: '#88/Spec pass/Docs' }).node.path === 'Later/Spec pass/Docs')
  check('agent move: --agent ... --label again on the moved agent → nothing structural (exists for --under)', codes(w.call({ agent: 'spec-88', label: 'Spec pass', under: 'n88' })).includes('exists') && w.call({ key: 'spec-88' }).node.path === 'Later/Spec pass')
})

// ================================================================= --move-to and transient contexts (§3.8, Q44, Q45)
await section(() => {
  const w = world()
  w.call({ key: 'tests', label: 'Tests' })
  const pend = w.call({ key: 'pend', label: 'Pending', under: 'tests', transient: true })
  check('transient: --transient marks a NEW context (create record transient:true)', pend.node.transient && pend.records[0].transient === true)
  for (const k of ['t1', 't2', 't3']) w.call({ key: k, label: k.toUpperCase(), under: 'pend' })
  const s = w.sess()
  const r1 = w.call({ key: 't1', move_to: '../In progress' })
  check('move-to: a missing bucket is CREATED transient (creator = the caller), then the node moves there, last', r1.ok && J(ops(r1)) === J(['create', 'move']) && r1.records[0].transient === true && r1.records[0].c === s.rootId && r1.node.path === 'Tests/In progress/T1', J(r1.records))
  const retry = w.call({ key: 't1', move_to: '../In progress' })
  check('move-to: a RETRY is a no-op move (no record, nothing created)', retry.ok && retry.records.length === 0 && !retry.moved)
  const ip = w.node('Tests/In progress')
  const r2 = w.call({ key: 't1', move_to: '../Passed' })
  check('vanish: the last child leaving a transient context removes it — entry stub then remove why:transient', r2.ok && J(ops(r2)) === J(['create', 'move', 'remove']) && r2.records[2].why === 'transient' && r2.records[2].n === ip.id && r2.entries.some(e => e.n === ip.id && /emptied/.test(e.text)), J(r2))
  check('vanish: it is a GHOST now (history kept), its key still held', s.ghosts.has(ip.id) && !s.nodes.has(ip.id))
  const r3 = w.call({ key: 't2', move_to: '../In progress' })
  check('resurrect: --move-to into a vanished bucket brings the SAME id back (create run:true), transient again', r3.ok && r3.records[0].op === 'create' && r3.records[0].n === ip.id && r3.records[0].run === true && r3.records[0].transient === true && s.nodes.get(ip.id).runs === 2 && !s.ghosts.has(ip.id))
  w.call({ key: 't2', move_to: '../Failed' })
  w.call({ key: 't3', move_to: '../In progress' })
  const r4 = w.call({ key: 't3', move_to: '../Passed' })
  check('vanish: Pending and In progress vanish once empty (Pending when its last test left)', r4.ok && !w.node('Tests/Pending') && !w.node('Tests/In progress') && s.ghosts.has(pend.node.id))
  check('move-to: the test run leaves Passed + Failed, one id each for their whole life', w.tree() === J({ label: 'Bridget', kids: [{ label: 'Tests', kids: [{ label: 'Passed', transient: true, kids: [{ label: 'T1', kids: [] }, { label: 'T3', kids: [] }] }, { label: 'Failed', transient: true, kids: [{ label: 'T2', kids: [] }] }] }] }), w.tree())
  check('move-to: a non-transient context that empties never vanishes (Tests, a plain node)', (() => { w.call({ key: 'plain', label: 'Plain' }); w.call({ key: 'pk', label: 'PK', under: 'plain' }); w.call({ key: 'pk', move_to: '/Elsewhere' }); return !!w.node('Plain') })())
  check('transient: a transient context that never had a child does not vanish', (() => { w.call({ key: 'lonely', label: 'Lonely', transient: true }); return !!w.node('Lonely') })())
  // refusals (Q45 and the --move rules)
  const snap0 = snap(s)
  const bare = w.call({ key: 't1', move_to: 'Passed' })
  check('Q45: a BARE destination is refused bad-path, suggesting "../X" and "/…/X"; nothing written', bare.code === 'bad-path' && bare.what.includes('"../Passed"') && bare.what.includes('"/…/Passed"') && snap(s) === snap0, bare.what)
  check('Q45: ../A/B (more segments than ..) and ../../X (fewer) are refused too (not retry-safe)', w.call({ key: 't1', move_to: '../A/B' }).code === 'bad-path' && w.call({ key: 't1', move_to: '../../X' }).code === 'bad-path')
  check('Q45: "..", "../.." alone and "./X" are refused', ['..', '../..', './X'].every(p => w.call({ key: 't1', move_to: p }).code === 'bad-path'))
  check('Q46 FINAL: ../../R/X is refused too — only "/…" and single-step "../X" (the refusal keeps rel for the suggest)', M.parseMoveTo('../../R/X').code === 'bad-path' && M.parseMoveTo('../../R/X').rel.up === 2 && M.parseMoveTo('../X').ok && M.parseMoveTo('/A/X').ok)
  check('move-to: a quoted ".." is a LABEL, not navigation', (() => { const p = M.parseMoveTo('../".."'); return p.ok && p.up === 1 && J(p.segs) === J(['..']) })())
  check('move-to: going above the session root → bad-path', w.call({ key: 'tests', move_to: '../X' }).code === 'bad-path' && snap(s) === snap0)
  w.call({ key: 'clash', label: 'T1', under: 'Tests/Failed' })
  const snap1 = snap(s)
  const dl = w.call({ key: 't1', move_to: '../Failed' })
  check('move-to: a same-label child at the destination → duplicate-label; nothing written (state identical)', dl.code === 'duplicate-label' && !!w.node('Tests/Passed/T1') && snap(s) === snap1)
  check('move-to: absolute "/…" from the session root (even with --agent)', (() => { w.call({ agent: 'runner', label: 'Runner' }); const r = w.call({ agent: 'runner', key: 'job', label: 'Job' }); const m = w.call({ agent: 'runner', key: 'job', move_to: '/Jobs/Done' }); return r.ok && m.ok && m.node.path === 'Jobs/Done/Job' && m.records[0].c === w.call({ key: 'runner' }).node.id })())
  check('move-to: the session root cannot move', w.call({ move_to: '/X' }).code === 'bad-move')
  check('move-to: under itself → bad-move', w.call({ key: 'tests', move_to: '/Tests/Passed/Inner' }).code === 'bad-move')
  // permanence
  w.call({ key: 'k1', label: 'K1', under: 'Tests/Failed' })
  const keep = w.call({ key: 'Failed', keep: true })
  check('keep: --keep makes a transient context permanent (one keep record)', keep.ok && J(ops(keep)) === J(['keep']) && !w.node('Tests/Failed').transient)
  w.call({ key: 'k1', move_to: '/Tests/Passed' }); w.call({ key: 'clash', move_to: '/Tests/Passed' })
  w.call({ key: 't2', move_to: '/Tests/Passed' })
  check('keep: a kept context no longer vanishes when emptied', !!w.node('Tests/Failed'))
  const rn = w.call({ key: 'Passed', rename: 'Passed tests' })
  check('keep: a RENAME makes it permanent (label + keep records)', rn.ok && J(ops(rn)) === J(['label', 'keep']) && !w.node('Tests/Passed tests').transient)
  check('transient: --transient on an existing node → warning exists (ignored)', codes(w.call({ key: 'tests', transient: true })).includes('exists'))
})

// ================================================================= grace period (Q44)
await section(() => {
  const w = world()
  w.call({ key: 'tests', label: 'Tests' })
  w.call({ key: 'pend', label: 'Pending', under: 'tests' })   // permanent: only In progress has a grace here
  w.call({ key: 'a', label: 'A', under: 'pend' }); w.call({ key: 'b', label: 'B', under: 'pend' })
  const r = w.call({ key: 'a', move_to: '../In progress', transient: '30s' })
  check('grace: --transient=30s with --move-to applies to the bucket it creates (grace_ms on the create)', r.ok && r.records[0].transient === true && r.records[0].grace_ms === 30000 && !codes(r).includes('exists'), J(r))
  const s = w.sess(), ip = w.node('Tests/In progress')
  const r2 = w.call({ key: 'a', move_to: '../Passed' })
  check('grace: emptied, it does NOT vanish at once — it is marked empty_since (no record)', r2.ok && !r2.records.some(x => x.op === 'remove') && s.nodes.get(ip.id).empty_since === w.at() - 1)
  check('grace: the sweep before the grace has passed leaves it', M.sweepTransients(w.st, w.at() + 10000).records.length === 0 && s.nodes.has(ip.id))
  w.tick(15000)
  w.call({ key: 'b', move_to: '../In progress' })
  check('grace: something ARRIVING during the grace keeps it (the mark is cleared)', s.nodes.get(ip.id).empty_since === null && M.sweepTransients(w.st, w.at() + 60000).records.length === 0)
  w.call({ key: 'b', move_to: '../Passed' })
  const left = w.at()
  const sw = M.sweepTransients(w.st, left + 30000)
  check('grace: once the grace has passed with no child, the sweep removes it (entry stub + remove why:transient)', sw.records.length === 1 && sw.records[0].op === 'remove' && sw.records[0].why === 'transient' && sw.entries.length === 1 && !s.nodes.has(ip.id) && s.ghosts.has(ip.id), J(sw))
  const nog = w.call({ key: 'solo', label: 'Solo', transient: true })
  w.call({ key: 'c', label: 'C', under: 'solo' })
  const v = w.call({ key: 'c', move_to: '/Done' })
  check('grace: without one (the default) the context vanishes the moment it empties', nog.ok && !nog.node.grace_ms && v.records.some(x => x.op === 'remove' && x.n === nog.node.id))
  check('grace: the tool form transient:"30s" is parsed; a bare number / junk is refused', M.parseCall({ transient: '30s' }).q.transient.grace_ms === 30000 && M.parseCall({ transient: '30' }).code === 'bad-input' && M.parseCall({ transient: 'soon' }).code === 'bad-input' && M.parseCall({ transient: true }).q.transient.grace_ms === null)
  // a chain: parent and child both transient with grace
  w.call({ key: 'outer', label: 'Outer', transient: '10s' })
  w.call({ key: 'inner', label: 'Inner', under: 'outer', transient: '10s' })
  w.call({ key: 'leaf', label: 'Leaf', under: 'inner' })
  w.call({ key: 'leaf', move_to: '/Done' })
  const t0 = w.at()
  const s1 = M.sweepTransients(w.st, t0 + 10000)
  check('grace: bottom-up — the inner vanishes after ITS grace, then the outer starts its own', s1.records.length === 1 && !w.node('Outer/Inner') && !!w.node('Outer') && s.nodes.get(w.call({ key: 'outer' }).node.id).empty_since === t0 + 10000)
  const s2 = M.sweepTransients(w.st, t0 + 20000)
  check('grace: …and the outer goes one grace period later', s2.records.length === 1 && !w.node('Outer'))
})

// ================================================================= atomicity
await section(() => {
  const w = world()
  w.call({ key: 'a', label: 'A' })
  const s = w.sess(), snap0 = snap(s)
  const r = w.call({ path: 'New/Deep/Tail', move: 'nowhere' })
  check('atomic: a refused verb undoes the path it created (nothing in the tree, no records)', r.code === 'unknown-node' && snap(s) === snap0)
  const r2 = w.call({ key: 'fresh', label: 'Fresh', move_to: '../X' })
  check('atomic: a refused --move-to undoes the target it created too', r2.code === 'bad-path' && snap(s) === snap0)
  const st2 = M.createModel({ origin: 'H' })
  const r3 = M.applyCall(st2, BRIDGET, { key: 'k' }, T0)
  check('atomic: a refused first call leaves no session behind', r3.code === 'label-required' && st2.sessions.size === 0)
  check('call: a session needs a name', M.applyCall(st2, { session: '' }, {}, T0).code === 'bad-session')
})

console.log(`\n${pass} passed, ${fail} failed`)
process.exit(fail ? 1 : 0)
