// Fast UNIT tests for #88 (v2.0) build step 2b — lines, entries, plans, the ROLLUP rule, questions, TYPES (node + message
// types; groups) and Q46 (resolve + the refused move's `suggest`) in lib/activity2.js (docs/spec-88.md §4.0, §5.7, §3.8,
// §1.7). Pure: no bridge, no sockets; time is passed in.
import { testOnly } from '../helpers/check.mjs'
import * as M from '../../lib/activity2.js'
let pass = 0, fail = 0
const check = (n, c, x = '') => { if (!testOnly(n)) return; let ok = false; try { ok = typeof c === 'function' ? !!c() : !!c } catch (e) { x = `threw: ${e && e.message} ${x}` } ok ? (pass++, console.log('PASS', n)) : (fail++, console.log('FAIL', n, x)) }
const J = JSON.stringify
async function section(fn) { try { await fn() } catch (e) { fail++; console.log('FAIL section crashed:', (e && e.stack) || e) } }
const BRIDGET = { session: 'Bridget', project: 'AIMB', user: 'robin' }
const T0 = 1790984000000
const DASH = { kind: 'dashboard', user: 'robin', host: 'ROBIN-Z790' }
function world(origin = 'ROBIN-Z790') {
  const st = M.createModel({ origin })
  let now = T0
  const call = (x, o) => M.applyCall(st, BRIDGET, x, now++, o)
  const sess = () => M.getSession2(st, BRIDGET)
  const tick = ms => { now += ms; return now }
  const at = () => now
  const get = key => { const s = sess(), id = s.scope.get(s.rootId + '\n' + key.toLowerCase()); return id ? s.nodes.get(id) : null }
  const byPath = p => M.findPath(sess(), p)
  const bar = n => M.bar2(sess(), typeof n === 'string' ? get(n) : n)
  return { st, call, sess, tick, at, get, byPath, bar }
}
const snap = s => J({ n: [...s.nodes.values()].map(n => [n.id, n.parent, n.label, n.type, n.current, n.progress, n.plan, n.log.length, n.transient]).sort(), k: [...s.kids].map(([k, v]) => [k, [...v].sort()]).sort(),
  l: [...s.labels].sort(), sc: [...s.scope].sort(), a: [...s.aliases].sort(), g: [...s.ghosts.keys()].sort() })
const codes = r => (r.warnings || []).map(w => w.code)
const ops = r => (r.records || []).map(x => x.op)

// ================================================================= the leading-@ rule (§4.0, Q36, Q33)
await section(() => {
  const w = world()
  w.call({ key: 'docs', label: 'Docs' })
  const plain = w.call({ key: 'docs', text: 'reading the spec' })
  check('@ rule: plain text only LOGS (current:false, line:false), the node keeps no line', plain.ok && plain.logged && !plain.current && !plain.line && w.get('docs').current === null && plain.entries[0].text === 'reading the spec' && plain.entries[0].current === false, J(plain))
  const set = w.call({ key: 'docs', text: '@Writing the docs' })
  check('@ rule: a leading @ also SETS the line ("Writing the docs", current + line)', set.current && set.line && w.get('docs').current.text === 'Writing the docs' && set.entries[0].text === 'Writing the docs' && set.entries[0].current === true)
  const lit = w.call({ key: 'docs', text: '@@home' })
  check('@ rule: @@x logs a literal "@x" and leaves the line', lit.entries[0].text === '@home' && !lit.current && w.get('docs').current.text === 'Writing the docs')
  const lit3 = w.call({ key: 'docs', text: '@@@home' })
  check('@ rule: @@@x sets the line to "@x"', lit3.line && w.get('docs').current.text === '@home')
  const mid = w.call({ key: 'docs', text: 'mail me@home' })
  check('@ rule: an @ anywhere else is just a character (plain)', !mid.current && mid.entries[0].text === 'mail me@home')
  check('@ rule: the 1.7x @~ is refused legacy-form, naming the 2.0 form', (r => r.code === 'legacy-form' && /--text "@/.test(r.what))(w.call({ key: 'docs', text: '@~root done' })))
  check('@ rule: "@" with nothing after it → text-empty', w.call({ key: 'docs', text: '@' }).code === 'text-empty')
  // Q33: one rule — a finishing state with plain text keeps the line's TEXT
  const fin = w.call({ key: 'docs', state: 'done', text: 'all sections written' })
  const n = w.get('docs')
  check('Q33: state done + PLAIN text: logs the text, the state changes, the line TEXT stays (no implied line)', fin.ok && !fin.line && fin.current && n.current.text === '@home' && n.current.state === 'done' && fin.entries[0].text === 'all sections written' && fin.entries[0].line_text === '@home', J(fin.entries[0]))
  const fin2 = w.call({ key: 'docs', state: 'done', text: '@Docs finished' })
  check('Q33: …"@<summary>" with the state sets both (what the 2.0 guide teaches)', fin2.line && n.current.text === 'Docs finished' && n.current.state === 'done' && !('line_text' in fin2.entries[0]))
  const tick = w.call({ key: 'docs', state: 'running' })
  check('a state alone is a TICK: the line keeps its text; the entry logs the line text', tick.current && !tick.line && n.current.text === 'Docs finished' && n.current.state === 'running' && tick.entries[0].text === 'Docs finished')
  const pr = w.call({ key: 'docs', progress: '3/6 pages' })
  check('progress alone: the bar moves, the entry text is the {progress} template, the line is untouched', pr.ok && !pr.current && pr.entries[0].text === '{progress}' && n.progress.done === 3 && n.current.state === 'running')
  check('progress "none" clears the bar (recorded as null)', (r => r.entries[0].progress === null && n.progress === null)(w.call({ key: 'docs', progress: 'none', text: 'bar cleared' })))
  check('details / data / stale_after alone (no report) → bad-input', w.call({ key: 'docs', details: 'x' }).code === 'bad-input' && w.call({ key: 'docs', stale_after: '1h' }).code === 'bad-input')
  const det = w.call({ key: 'docs', text: '@with details', details: 'the long story', data: { a: 1 } })
  check('details / data go on the entry, and on the line when its text is set', det.entries[0].details === 'the long story' && det.entries[0].data.a === 1 && n.current.details === 'the long story' && n.current.data.a === 1)
  w.call({ key: 'docs', state: 'blocked' })
  check('…a state change KEEPS the line\'s details / data', n.current.details === 'the long story' && n.current.data.a === 1)
  const quiet = w.call({ key: 'docs', text: '@quiet', log: false })
  check('log:false: the board changes, no entry is written (logged:false, id null, cp_dirty for step 3)', quiet.ok && !quiet.logged && quiet.id === null && quiet.entries.length === 0 && n.current.text === 'quiet' && n.cp_dirty === true)
  const long = w.call({ key: 'docs', text: 'x'.repeat(300) })
  check('text over 240 code points is cut with "…" and warning text-truncated', codes(long).includes('text-truncated') && [...long.entries[0].text].length === 240)
  check('a ☐-less context can\'t be skipped (not-a-plan-item); todo / skipped on the session → bad-agent-state', w.call({ key: 'docs', state: 'skipped' }).code === 'not-a-plan-item' && w.call({ state: 'todo' }).code === 'bad-agent-state')
  check('abandoned on the session holding no plan → not-a-plan', w.call({ state: 'abandoned' }).code === 'not-a-plan')
})

// ================================================================= entries (§2.2), activity, permanence
await section(() => {
  const w = world()
  const c = w.call({ key: 'docs', label: 'Write the docs', text: '@starting' })
  const e = c.entries[0], node = w.get('docs')
  check('entry: a v6 entry { v:6, id, ts, n, type:"note", current, text, state, at, …ident, details, data }', e.v === 6 && /^act_/.test(e.id) && e.n === node.id && e.type === 'note' && e.at === 'Write the docs' && e.state === 'running' && e.session === 'Bridget' && e.host === 'ROBIN-Z790' && e.s0 === T0 && e.details === null && e.data === null && c.id === e.id, J(e))
  check('writes: the create record comes before the entry that names its node (one ordered list)', J(c.writes.map(x => x.op || 'entry')) === J(['create', 'entry']) && c.records.length === 1 && c.entries.length === 1)
  check('result names the node (§4.2): node { id, key, label, path, kind, type, created }, state, stale_at', c.node.created === true && c.node.type === 'context' && c.state === 'running' && c.node.key === 'docs')
  check('the node keeps a small in-memory log (no identity, no details)', node.log.length === 1 && node.log[0].id === e.id && !('session' in node.log[0]))
  // at: the path when written, capped at 1 KB
  let parent = null
  for (let i = 0; i < 20; i++) { const r = w.call({ key: `d${i}`, label: `${i} ${'x'.repeat(56)}`, ...(parent ? { under: parent } : {}) }); parent = `d${i}` }
  const deep = w.call({ key: 'd19', text: 'deep' })
  check('at: a path over 1 KB is cut in the MIDDLE to ≤ 1024 bytes (head + "…" + tail)', Buffer.byteLength(deep.entries[0].at) <= 1024 && deep.entries[0].at.includes('…') && deep.entries[0].at.startsWith('0 x') && deep.entries[0].at.endsWith('x'.repeat(20)))
  // structural entries are real entries now
  w.call({ key: 'later', label: 'Later' })
  const mv = w.call({ key: 'docs', move: 'later' }, { by: DASH, act: 'move' })
  const me = mv.entries[0]
  check('structural entry: a move writes an `event` entry "moved by robin via dashboard (…) from … to …" (act move, at = the new path)', me && me.type === 'event' && me.act === 'move' && /^moved by robin via dashboard \(ROBIN-Z790\) from Write the docs to Later\/Write the docs$/.test(me.text) && me.at === 'Later/Write the docs' && me.by.user === 'robin', J(me))
  check('…and the move record carries by / act (a dashboard did it)', mv.records[0].op === 'move' && mv.records[0].by.user === 'robin' && mv.records[0].act === 'move')
  // activity (§1.4)
  const w2 = world()
  w2.call({ agent: 'lead', label: 'Lead' })
  w2.call({ agent: 'lead', key: 'k', label: 'K' })
  const s = w2.sess(), lead = [...s.nodes.values()].find(n => n.kind === 'agent'), k = [...s.nodes.values()].find(n => n.key === 'k')
  w2.tick(60000)
  w2.call({ agent: 'lead', key: 'k', text: 'working', stale_after: '2h' })
  check('activity: a report refreshes target..owner (the agent) with stale_after; the root stays implicit', k.last_activity === w2.at() - 1 && lead.last_activity === w2.at() - 1 && lead.stale_after_ms === 7200000 && M.rootOf(s).implicit === true)
  w2.tick(60000)
  w2.call({ agent: 'lead', key: 'k', text: 'by the bridge' }, { by: 'bridge' })
  check('activity: a SYSTEM call (by) refreshes nothing, and its entry is attributed', lead.last_activity < w2.at() - 1 && k.log[k.log.length - 1].by === 'bridge')
  // agents finish and revive
  const done = w2.call({ agent: 'lead', state: 'done', text: '@all done' })
  check('agent: a done line FINISHES it (finished_at, on the entry too); its ETA is dropped', lead.finished_at === w2.at() - 1 && done.entries[0].finished_at === lead.finished_at)
  const rev = w2.call({ agent: 'lead', state: 'running', text: '@back at it' })
  check('agent: a running line revives it (finished_at null, recorded as null; a line without a state keeps the state, as 1.7x)', lead.finished_at === null && rev.entries[0].finished_at === null)
  // transient + own line
  const w3 = world()
  w3.call({ key: 'b', label: 'Bucket', transient: true })
  w3.call({ key: 'b', text: 'only a log line' })
  check('transient: plain text on it does NOT make it permanent', w3.get('b').transient === true)
  const own = w3.call({ key: 'b', text: '@its own line' })
  check('transient: its OWN line (a leading @) makes it permanent — one keep record', w3.get('b').transient === false && ops(own).includes('keep'))
})

// ================================================================= plans (§4.1, 6b / 6c / #79 on ids)
await section(() => {
  const w = world()
  const p = w.call({ key: 'rel', label: 'Release', plan: [{ key: 'spec', label: 'Spec' }, { key: 'build', label: 'Build' }, 'Test', 'Docs', 'Ship'] })
  const s = w.sess(), rel = w.get('rel')
  check('plan: items are created under the target, in order, each a ☐ todo plan item with a logged entry', p.ok && J(p.plan.map(i => i.label)) === J(['Spec', 'Build', 'Test', 'Docs', 'Ship']) && p.plan.every(i => i.created && i.plan_item && i.state === 'todo') && p.entries.length === 5 && p.entries.every(e => e.current && e.state === 'todo'), J(p.plan))
  check('plan: create records carry plan_item + plan_ix; label-only items get the slug key in the caller\'s scope', p.records.filter(r => r.plan_item).length === 5 && p.records[3].plan_ix === 2 && p.plan[2].key === 'Test' && !!w.get('Test'))
  check('plan: the children sort as given (derived ranks: creation time + plan position)', J(M.childrenOf2(s, rel).map(c => c.label)) === J(['Spec', 'Build', 'Test', 'Docs', 'Ship']))
  const re = w.call({ key: 'rel', plan: ['Spec', 'Test', { key: 'ret', label: 'Retro' }] })
  check('re-plan: an existing item is kept untouched (matched by label / key), a new one added at the end', re.ok && J(re.plan.map(i => [i.label, i.created])) === J([['Spec', false], ['Test', false], ['Retro', true]]) && M.childrenOf2(s, rel).at(-1).label === 'Retro')
  check('plan: a NEW keyed item without a label → label-required, the whole call refused (Q31)', (r => r.code === 'label-required' && !w.get('nolabel'))(w.call({ key: 'rel', plan: [{ key: 'ok1', label: 'Ok 1' }, { key: 'nolabel' }] })) && !w.get('ok1'))
  w.call({ key: 'misc', label: 'Misc' })
  const el = w.call({ key: 'rel', plan: [{ key: 'misc', label: 'Misc' }] })
  check('plan: a key held ELSEWHERE in the scope makes nothing — exists-elsewhere (§3.5)', el.ok && el.plan[0].warning === 'exists-elsewhere' && !el.plan[0].created && codes(el).includes('exists-elsewhere'))
  w.call({ key: 'adopt', label: 'Adopt me', under: 'rel' })
  w.call({ key: 'lined', label: 'Has a line', under: 'rel', text: '@busy' })
  const ad = w.call({ key: 'rel', plan: ['Adopt me', 'Has a line'] })
  check('plan: an ordinary line-less context is ADOPTED (an item record + ☐ line); one with a line is left alone', ad.plan[0].adopted && ad.plan[0].plan_item && ops(ad).includes('item') && !ad.plan[1].plan_item && w.get('lined').current.text === 'busy')
  // N of M with skipped / abandoned (#79)
  const w2 = world()
  w2.call({ key: 'p', label: 'P', plan: ['A', 'B', 'C', 'D', 'E'] })
  w2.call({ key: 'A', state: 'done' }); w2.call({ key: 'B', state: 'done' }); w2.call({ key: 'C', state: 'skipped' }); w2.call({ key: 'D', state: 'abandoned' })
  const b = w2.bar('p')
  check('N of M: every item counts in M — done → done, skipped + abandoned → skipped (#79): 2 of 5, 2 skipped (1 abandoned)', b.done === 2 && b.skipped === 2 && b.total === 5 && b.abandoned === 1 && b.items && b.unit === 'done', J(b))
  const pl = M.planOf2(w2.sess(), w2.get('p'))
  check('plan end: skipped / abandoned / todo items keep the plan OPEN', pl.open === 1 && M.planEndAt2(w2.sess(), w2.get('p')) === null)
  w2.call({ key: 'E', state: 'done' })
  check('plan end: … still open while not EVERY item is done (skipped C)', M.planEndAt2(w2.sess(), w2.get('p')) === null)
  w2.call({ key: 'C', state: 'done' }); w2.call({ key: 'D', state: 'done' })
  const endAt = M.planEndAt2(w2.sess(), w2.get('p'))
  check('plan end: every item done → ended at the last one\'s time, how "all-done"', endAt === w2.at() - 1 && M.planEndHow2(w2.sess(), w2.get('p')) === 'all-done')
  const w3 = world()
  w3.call({ key: 'p', label: 'P', plan: ['A', 'B'] })
  w3.call({ key: 'p', state: 'done', text: '@shipped' })
  check('plan end: a CONTEXT plan node\'s own line set done ends it ("done"); its bar is then forced full', M.planEndHow2(w3.sess(), w3.get('p')) === 'done' && w3.bar('p').forced === 'done' && w3.bar('p').pct === 100)
  w3.call({ agent: 'ag', label: 'Agent' })
  w3.call({ agent: 'ag', plan: ['X', 'Y'] })
  const ab = w3.call({ agent: 'ag', state: 'abandoned', text: '@giving up' })
  const ag = [...w3.sess().nodes.values()].find(n => n.kind === 'agent')
  check('plan end: abandoned on an AGENT holding a plan finishes it AND sets its plan-end marker (6d)', ab.ok && ag.plan_end && ag.plan_end.state === 'abandoned' && ag.finished_at && M.planEndHow2(w3.sess(), ag) === 'abandoned' && ab.entries[0].plan_end === 'abandoned')
  check('plan end: …and CASCADES to its open items (each "abandoned with Agent")', ab.cascade && ab.cascade.length === 2 && ab.entries.slice(1).every(e => e.state === 'abandoned' && /^abandoned with Agent/.test(e.text)))
  const w4 = world()
  w4.call({ key: 'first', label: 'First', state: 'todo' })
  check('6b: todo as a line-less context\'s first state makes it a plan item (an item record)', w4.get('first').plan === true)
  // cascade (not crossing an agent), with an open question withdrawn
  const w5 = world()
  w5.call({ key: 'top', label: 'Top', plan: ['I1', 'I2'] })
  w5.call({ key: 'I1', state: 'done' })
  w5.call({ key: 'sub', label: 'Sub', under: 'top', text: '@running sub' })
  w5.call({ key: 'q', label: 'Q', under: 'sub', ask: 'Which way?', choices: ['Left', 'Right'] })
  w5.call({ agent: 'helper', label: 'Helper', under: 'top' })
  w5.call({ agent: 'helper', key: 'hk', label: 'HK', text: '@helper work' })
  const ca = w5.call({ key: 'top', state: 'abandoned', text: '@dropped' })
  check('cascade: abandoning a context abandons its OPEN descendants (deepest first), not a done item, not across an agent', ca.cascade && J(ca.cascade.map(c => c.path).sort()) === J(['Top/I2', 'Top/Sub', 'Top/Sub/Q'].sort()) && w5.get('I1').current.state === 'done' && [...w5.sess().nodes.values()].find(n => n.key === 'hk').current.state === 'running', J(ca.cascade))
  check('cascade: an OPEN question in it is WITHDRAWN (status withdrawn, a withdrawal entry)', w5.get('q').current.question.status === 'withdrawn' && ca.entries.some(e => e.n === w5.get('q').id && e.type === 'withdrawal'))
  // ranks where needed
  const w6 = world()
  const st6 = w6.st, I = BRIDGET
  M.applyCall(st6, I, { key: 'pp', label: 'PP', plan: ['a1', 'a2', 'a3'] }, T0 + 5000)
  const late = M.applyCall(st6, I, { key: 'pp', plan: ['b1'] }, T0 + 5000)   // the SAME ms: b1's derived rank (plan_ix 0) would sort before a2 / a3
  check('ranks: an item whose derived rank would sort before an existing item gets a stored rank after the last (only where needed)', late.records[0].rank !== null && J(M.childrenOf2(w6.sess(), w6.get('pp')).map(c => c.label)) === J(['a1', 'a2', 'a3', 'b1']) && !M.childrenOf2(w6.sess(), w6.get('pp'))[0].rank)
})

// ================================================================= ROLLUP (Robin 2026-10-03: reverses 6c decision 7)
await section(() => {
  const w = world()
  w.call({ key: 'p88', label: 'P88', text: '@building', plan: ['Spec', 'Build 1', 'Build 2a'] })
  w.call({ key: 'Spec', state: 'done' }); w.call({ key: 'Build-1', state: 'done' }); w.call({ key: 'Build-2a', text: '@in progress' })
  for (const a of ['spec88', 'q88']) {
    w.call({ agent: a, label: a, under: 'p88' })
    w.call({ agent: a, plan: ['r1', 'r2', 'r3'] })
    for (const k of ['r1', 'r2', 'r3']) w.call({ agent: a, key: k, state: 'done' })
    w.call({ agent: a, state: 'done', text: '@finished' })
  }
  w.call({ key: 'notes', label: 'Notes', under: 'p88', text: 'notes', progress: '9/10 done' })
  const b = w.bar('p88')
  check('ROLLUP (#88 case): an OPEN plan whose node also holds FINISHED helper agents (full bars) and a context with its own bar shows ONLY its items: 2 of 3', b && b.done === 2 && b.total === 3 && b.items && b.pct < 100 && !b.forced, J(b))
  const sess = w.sess(), helpers = M.childrenOf2(sess, w.get('p88')).filter(c => c.kind === 'agent')
  check('ROLLUP: …the helpers keep their own full bars on their own rows', helpers.length === 2 && helpers.every(h => M.bar2(sess, h).pct === 100))
  const w2 = world()
  w2.call({ key: 'mix', label: 'Mix' })
  w2.call({ key: 'o1', label: 'O1', under: 'mix', text: 'x', progress: '3/6 files' })
  w2.call({ key: 'o2', label: 'O2', under: 'mix', text: 'x', progress: '1/2 files' })
  check('ROLLUP: a node with NO plan items rolls up as before — the SUM of its children sharing a unit (4 of 8 files)', (r => r.done === 4 && r.total === 8 && r.unit === 'files' && !r.items)(w2.bar('mix')))
  w2.call({ key: 'o3', label: 'O3', under: 'mix', text: 'x', progress: '50%' })
  check('ROLLUP: … else their MEAN % (mixed units)', (r => r.unit === '%' && r.total === 100)(w2.bar('mix')))
  w2.call({ key: 'mix', plan: ['Only item'] })
  check('ROLLUP: once it holds a plan item, its bar is its items only (0 of 1), the ordinary children no longer mix in', (r => r.items && r.done === 0 && r.total === 1)(w2.bar('mix')))
  check('ROLLUP: a question under a plan node counts as one of its items', (() => { w2.call({ key: 'qq', label: 'QQ', under: 'mix', ask: 'Ship?', choices: ['Yes', 'No'] }); const r = w2.bar('mix'); return r.total === 2 && r.done === 0 })())
})

// ================================================================= TYPES: nodes (registry), groups, plans
await section(() => {
  check('registry: node types context | plan | group | question | agent | session | test-run (reserved until 2d); each with fields, glyph, show, bar, counts_as, children and a #92 menu slot',
    J(Object.keys(M.NODE_TYPES).sort()) === J(['agent', 'context', 'group', 'plan', 'question', 'session', 'test-run']) && !M.NODE_TYPES['test-run'].reserved && Object.values(M.NODE_TYPES).every(T => Array.isArray(T.fields) && T.glyph && T.show && T.bar && T.counts_as && Array.isArray(T.menu)) && Object.isFrozen(M.NODE_TYPES.group))
  check('parseContextType: case-insensitive; test-run accepted (2d); agent → bad-type; question only with --ask', M.parseContextType('GROUP').type === 'group' && M.parseContextType('Test-Run').type === 'test-run' && M.parseContextType('agent').code === 'bad-type' && M.parseContextType('question').code === 'bad-type' && M.parseContextType('question', { ask: true }).ok && M.parseContextType('nope').code === 'bad-type')
  const w = world()
  w.call({ key: 'rel', label: 'Next release', context_type: 'plan', plan: ['A', 'B'] })
  const g = w.call({ key: 'qs', label: 'Questions', under: 'rel', context_type: 'Group' })
  check('group: --context-type=group at creation (type on the create record and on the node)', g.ok && g.node.type === 'group' && g.records[0].type === 'group' && w.get('qs').type === 'group')
  for (const [k, l] of [['g1', 'One'], ['g2', 'Two'], ['g3', 'Three'], ['g4', 'Four']]) w.call({ key: k, label: l, under: 'qs', text: '@open' })
  const s = w.sess(), qs = w.get('qs')
  check('group: NO bar (whatever it holds); in its place a COUNT — "4 items" while none is resolved', w.bar('qs') === null && M.groupCount2(s, qs).text === '4 items' && M.displayOf2(s, qs).show === 'count' && M.displayOf2(s, qs).count.n === 4)
  w.call({ key: 'g1', state: 'done' })
  check('group: … "3 open · 1 done"', M.groupCount2(s, qs).text === '3 open · 1 done')
  w.call({ key: 'g2', state: 'abandoned' })
  check('group: ABANDONED children are not counted', M.groupCount2(s, qs).text === '2 open · 1 done' && M.groupCount2(s, qs).n === 3)
  check('group: the viewer\'s HIDDEN rows are not counted', M.groupCount2(s, qs, { hidden: new Set([w.get('g3').id]) }).text === '1 open · 1 done')
  check('group: it adds NOTHING to its parent\'s rollup (the plan stays 0 of 2)', (r => r.total === 2 && r.done === 0)(w.bar('rel')))
  w.call({ key: 'gp', label: 'Group plan', context_type: 'group', plan: ['x1', 'x2'] })
  w.call({ key: 'x1', state: 'done' }); w.call({ key: 'x2', state: 'done' })
  check('group: its items keep their states, but it has NO plan end (planOf2 null) and no bar', M.planOf2(s, w.get('gp')) === null && M.planEndAt2(s, w.get('gp')) === null && w.bar('gp') === null && M.groupCount2(s, w.get('gp')).text === '2 done')
  check('group: it takes no progress (it has no bar) → bad-field', w.call({ key: 'qs', progress: '1/2' }).code === 'bad-field')
  check('group: --context-type on an EXISTING node is ignored with warning exists', (r => r.ok && codes(r).includes('exists') && J(r.warnings.find(x => x.code === 'exists').ignored) === J(['context_type']) && w.get('qs').type === 'group')(w.call({ key: 'qs', context_type: 'plan' })))
  check('types: an agent takes no --context-type; test-run is accepted since 2d', w.call({ agent: 'a1', label: 'A1', context_type: 'group' }).code === 'bad-input' && w.call({ key: 'tr', label: 'TR', context_type: 'test-run' }).node.type === 'test-run')
  // toggle (the dashboard's Show as group / Show as plan)
  const t1 = M.setType2(w.st, BRIDGET, qs.id, 'plan', w.tick(1), { by: DASH })
  check('toggle: Show as plan — one `type` record + an `event` entry ("shown by robin via dashboard (…) as a plan"), act show_as_plan', t1.ok && t1.records[0].op === 'type' && t1.records[0].type === 'plan' && t1.records[0].act === 'show_as_plan' && t1.entries[0].type === 'event' && /^shown by robin via dashboard \(ROBIN-Z790\) as a plan$/.test(t1.entries[0].text) && qs.type === 'plan', J(t1))
  check('toggle: its children kept their states; it now shows a bar slot, no count', w.get('g1').current.state === 'done' && w.get('g2').current.state === 'abandoned' && M.displayOf2(s, qs).show === 'bar' && M.groupCount2(s, qs) === null)
  check('toggle: back to a group; the same type again → no-change', M.setType2(w.st, BRIDGET, qs.id, 'group', w.tick(1), { by: DASH }).ok && M.setType2(w.st, BRIDGET, qs.id, 'GROUP', w.tick(1), { by: DASH }).code === 'no-change')
  check('toggle: a plan item can\'t become a group; an agent / question keep their types (bad-type)', M.setType2(w.st, BRIDGET, w.get('A').id, 'group', w.tick(1)).code === 'bad-type'
    && M.setType2(w.st, BRIDGET, [...s.nodes.values()].find(n => n.kind === 'agent' || n.type === 'session').id, 'plan', w.tick(1)).code === 'bad-type')
  // plan type: always "N of M"
  const w2 = world()
  w2.call({ key: 'pl', label: 'A plan', context_type: 'plan' })
  w2.call({ key: 'c1', label: 'C1', under: 'pl', text: 'x', progress: '5/5' })
  check('plan type: its bar is ALWAYS its items ("N of M") — ordinary children never mix in (none yet: no bar)', w2.bar('pl') === null)
  w2.call({ key: 'pl', plan: ['i1'] })
  check('plan type: … 0 of 1 once it has an item', (r => r.items && r.total === 1)(w2.bar('pl')))
  // ghosts keep their type
  const w3 = world()
  w3.call({ key: 'tests', label: 'Tests' })
  w3.call({ key: 'b1', label: 'Bucket', under: 'tests', context_type: 'group', transient: true })
  w3.call({ key: 't1', label: 'T1', under: 'b1' })
  w3.call({ key: 't1', move_to: '../Elsewhere' })
  check('types: a ghost keeps its type — a group bucket brought back by --move-to is a group again', (() => { w3.call({ key: 't1', move_to: '/Tests/Bucket' }); return w3.byPath('Tests/Bucket').type === 'group' })())
})

// ================================================================= TYPES: entries (message types)
await section(() => {
  check('registry: message types note (default) | question | answer | withdrawal | expiry | event | test-result (reserved until 2d)',
    J(Object.keys(M.MESSAGE_TYPES).sort()) === J(['answer', 'event', 'expiry', 'note', 'question', 'test-result', 'withdrawal']) && M.MESSAGE_TYPES.note.settable && !M.MESSAGE_TYPES.answer.settable && M.MESSAGE_TYPES['test-result'].settable && !M.MESSAGE_TYPES['test-result'].reserved)
  const v = M.validateEntryFields('test-result', { result: 'PASS', checks: '22', duration: '4.1s' })
  check('typed fields are VALIDATED and normalised (test-result: result pass, checks 22, duration 4.1s → 4100 ms)', v.ok && v.fields.result === 'pass' && v.fields.checks === 22 && v.fields.duration === 4100, J(v))
  check('typed fields: an unknown field, a bad enum or a negative int is refused bad-fields', M.validateEntryFields('test-result', { nope: 1 }).code === 'bad-fields' && M.validateEntryFields('test-result', { result: 'maybe' }).code === 'bad-fields' && M.validateEntryFields('test-result', { checks: -1 }).code === 'bad-fields')
  check('typed fields: answer takes choice / text / revised; note takes none (extras go in data)', M.validateEntryFields('answer', { choice: 'Yes', revised: 2 }).ok && M.validateEntryFields('note', { x: 1 }).code === 'bad-fields')
  const w = world()
  w.call({ key: 'k', label: 'K' })
  check('message_type: note is the default; given explicitly it is the same', (r => r.entries[0].type === 'note' && !('fields' in r.entries[0]))(w.call({ key: 'k', text: 'x', message_type: 'NOTE' })))
  check('message_type: a bridge type from a caller → bad-message-type; test-result is accepted since 2d (it needs its result); an unknown one → bad-message-type', w.call({ key: 'k', text: 'x', message_type: 'answer' }).code === 'bad-message-type' && w.call({ key: 'k', text: 'x', message_type: 'test-result' }).code === 'bad-fields' && w.call({ key: 'k', text: 'x', message_type: 'test-result', fields: { result: 'pass' } }).ok && w.call({ key: 'k', text: 'x', message_type: 'chat' }).code === 'bad-message-type')
  check('message_type / fields without a report → bad-input; fields on a note → bad-fields', w.call({ key: 'k', message_type: 'note' }).code === 'bad-input' && w.call({ key: 'k', text: 'x', fields: { a: 1 } }).code === 'bad-fields')
})

// ================================================================= questions (#85 / #90 on ids; type question)
await section(() => {
  const w = world()
  w.call({ agent: 'asker', label: 'Asker' })
  const a = w.call({ agent: 'asker', ask: 'Which database should the cache use?', choices: ['Postgres', 'SQLite'], free: true, details: 'background' })
  const s = w.sess(), q1 = [...s.nodes.values()].find(n => n.key === '?1')
  check('ask on an agent: a new child keyed ?1 in the ASKER\'s scope, labelled ?1, type question; line = the question, blocked', a.ok && q1 && q1.type === 'question' && q1.scope === 'asker' && q1.label === '?1' && q1.current.text === 'Which database should the cache use?' && q1.current.state === 'blocked' && a.question.status === 'asked' && a.node.key === '?1', J(a))
  const e = a.entries[0]
  check('ask: the entry is a `question` entry with typed fields (choices, free) and the line carries the question; details on the line', e.type === 'question' && J(e.fields.choices) === J(['Postgres', 'SQLite']) && e.fields.free === true && e.question.status === 'asked' && q1.current.details === 'background')
  const a2 = w.call({ agent: 'asker', ask: 'Ship today?', choices: ['Yes', 'No'] })
  check('ask: the next one is ?2 (the scope\'s highest + 1)', a2.node.key === '?2')
  check('ask: choices spelt out in the question → warning choices-in-question (Robin: state the question, list the options as answers)', codes(w.call({ agent: 'asker', ask: 'Postgres or SQLite?', choices: ['Postgres', 'SQLite'] })).includes('choices-in-question'))
  const own = w.call({ key: 'dbq', label: 'DB choice', ask: 'Which database?', choices: ['A', 'B'] })
  check('ask on a NEW key: that node IS the question (created type question; key dbq)', own.ok && own.node.key === 'dbq' && own.node.type === 'question' && own.records[0].type === 'question')
  w.call({ key: 'plainctx', label: 'Plain' })
  const conv = w.call({ key: 'plainctx', ask: 'Go?', choices: ['Yes', 'No'] })
  check('ask on a line-less leaf CONTEXT: it becomes the question (a `type` record)', conv.ok && conv.node.key === 'plainctx' && ops(conv).includes('type') && w.get('plainctx').type === 'question')
  check('ask on an OPEN question → question-open', w.call({ key: 'dbq', ask: 'Again?', choices: ['x', 'y'] }).code === 'question-open')
  check('a question: plain text LOGS on it; a @ line or a state on it → question-node; no plan / progress (bad-field)', w.call({ key: 'dbq', text: 'thinking' }).ok && w.call({ key: 'dbq', text: '@new line' }).code === 'question-node' && w.call({ key: 'dbq', state: 'done' }).code === 'question-node'
    && w.call({ key: 'dbq', plan: ['x'] }).code === 'bad-field' && w.call({ key: 'dbq', text: 'x', progress: '1/2' }).code === 'bad-field')
  check('a question holds nothing: a node under it is refused bad-child', w.call({ key: 'under-q', label: 'Under', under: 'dbq' }).code === 'bad-child')
  // the asker withdraws
  const lineId = w.get('dbq').current.id
  const wd = w.call({ key: 'dbq', state: 'withdrawn', text: 'not needed after all' })
  const dbq = w.get('dbq')
  check('withdraw (the asker): status withdrawn, state abandoned, the line KEEPS its id + text; a `withdrawal` entry with the note', wd.ok && dbq.current.question.status === 'withdrawn' && dbq.current.state === 'abandoned' && dbq.current.id === lineId && dbq.current.text === 'Which database?' && wd.entries[0].type === 'withdrawal' && wd.entries[0].fields.note === 'not needed after all' && /^withdrawn: not needed/.test(wd.entries[0].text) && wd.entries[0].line_id === lineId, J(wd.entries[0]))
  check('withdraw: an already-closed one → question-closed; a non-question → not-a-question', w.call({ key: 'dbq', state: 'withdrawn' }).code === 'question-closed' && w.call({ key: 'plainctx2', label: 'P2', state: 'withdrawn' }).code === 'not-a-question')
  // answer / change answer (the dashboard; 2c wires the action)
  const t1 = w.tick(10)
  const an = M.answerQuestion2(w.st, BRIDGET, q1.id, { choice: 'postgres', text: 'it is what the rest uses' }, t1, { by: DASH })
  check('answer: answered (state done), the choice matched case-insensitively, by + at; the LINE keeps its id / text / details', an.ok && q1.current.question.status === 'answered' && q1.current.state === 'done' && an.answer.choice === 'Postgres' && q1.current.question.by.user === 'robin' && q1.current.id === e.id && q1.current.details === 'background', J(an))
  const ae = an.entries[0]
  check('answer: an `answer` ENTRY (typed fields choice + text) naming the answer, with details of its own (#90)', ae.type === 'answer' && ae.fields.choice === 'Postgres' && ae.fields.text === 'it is what the rest uses' && /^answered by robin via dashboard \(ROBIN-Z790\): "Postgres" — note: it is what/.test(ae.text) && /^Answer: Postgres/.test(ae.details) && ae.by.user === 'robin')
  check('answer: a SYSTEM message — the asker\'s activity is not refreshed', [...s.nodes.values()].find(n => n.key === 'asker').last_activity < t1)
  check('answer: a closed question → question-closed; not one of the choices → bad-choice; free text on a choices-only one → bad-args',
    M.answerQuestion2(w.st, BRIDGET, q1.id, { choice: 'SQLite' }, w.tick(1), { by: DASH }).code === 'question-closed' && M.answerQuestion2(w.st, BRIDGET, a2.node.id, { choice: 'Maybe' }, w.tick(1), { by: DASH }).code === 'bad-choice' && M.answerQuestion2(w.st, BRIDGET, a2.node.id, { text: 'hm' }, w.tick(1), { by: DASH }).code === 'bad-args')
  const ch = M.answerQuestion2(w.st, BRIDGET, q1.id, { choice: 'SQLite' }, w.tick(1), { by: DASH, change: true })
  check('change answer: still answered, revised 1, previous = the old answer; an `answer` entry with revised', ch.ok && q1.current.question.revised === 1 && ch.previous.answer.choice === 'Postgres' && ch.entries[0].type === 'answer' && ch.entries[0].fields.revised === 1 && /^answer changed by robin/.test(ch.entries[0].text))
  check('change answer: the same answer again → no-change; on an open question → question-open', M.answerQuestion2(w.st, BRIDGET, q1.id, { choice: 'SQLite' }, w.tick(1), { by: DASH, change: true }).code === 'no-change' && M.answerQuestion2(w.st, BRIDGET, a2.node.id, { choice: 'Yes' }, w.tick(1), { by: DASH, change: true }).code === 'question-open')
  check('answer: needs a dashboard author (bad-by)', M.answerQuestion2(w.st, BRIDGET, a2.node.id, { choice: 'Yes' }, w.tick(1), {}).code === 'bad-by')
  const out = M.questionOutcome2(w.st, BRIDGET, q1.id)
  check('questionOutcome2 (the --wait view): answered, the answer, revised + previous', out.outcome === 'answered' && out.answer.choice === 'SQLite' && out.revised === 1 && out.key === '?1')
  // the dashboard's withdraw
  const dw = M.withdrawQuestion2(w.st, BRIDGET, a2.node.id, w.tick(1), { by: DASH })
  check('withdrawQuestion2 (the dashboard): withdrawn by robin; a `withdrawal` entry', dw.ok && dw.question.status === 'withdrawn' && dw.entries[0].type === 'withdrawal' && /^withdrawn by robin via dashboard/.test(dw.entries[0].text))
  // expiry + never stale while open
  const w2 = world()
  w2.call({ agent: 'lead', label: 'Lead', text: '@working' })
  const ex = w2.call({ agent: 'lead', ask: 'Proceed?', choices: ['Yes', 'No'], expires: '30m' })
  const s2 = w2.sess(), qn = s2.nodes.get(ex.node.id), lead = [...s2.nodes.values()].find(n => n.kind === 'agent')
  check('never stale while OPEN: the question has no stale_at even though its agent goes stale', M.staleAt2(s2, qn, 15) === null && M.effectiveState2(s2, qn, w2.at() + 3600000, 15).state === 'blocked' && M.effectiveState2(s2, lead, w2.at() + 3600000, 15).state === 'stale')
  check('nextQuestionExpiry2: the asked_at + 30 min', M.nextQuestionExpiry2(w2.st) === qn.current.question.expires_at && qn.current.question.expires_at === qn.current.question.asked_at + 1800000)
  check('expiry: nothing before its time', M.expireQuestions2(w2.st, qn.current.question.expires_at - 1).expired.length === 0)
  const xp = M.expireQuestions2(w2.st, qn.current.question.expires_at)
  check('expiry: expired by the bridge (state abandoned), an `expiry` entry "expired — nobody answered within 30m" (after_ms), no activity', xp.expired.length === 1 && qn.current.question.status === 'expired' && qn.current.state === 'abandoned' && xp.entries[0].type === 'expiry' && xp.entries[0].fields.after_ms === 1800000 && /^expired — nobody answered within 30m/.test(xp.entries[0].text) && xp.entries[0].by === 'bridge' && xp.expired[0].agent.key === 'lead', J(xp.entries[0]))
  check('a CLOSED question follows the rules again (an abandoned line: no stale_at); a new ask on it re-opens it there', M.staleAt2(s2, qn, 15) === null && w2.call({ id: qn.id, ask: 'Proceed now?', choices: ['Yes', 'No'] }).node.id === qn.id && qn.current.question.status === 'asked')
  check('merge refuses a node holding an OPEN question (2a rule, now with real questions)', (() => { w2.call({ key: 'm1', label: 'M1' }); w2.call({ key: 'm2', label: 'M2' }); return w2.call({ key: 'mq', label: 'MQ', under: 'm1', ask: 'Hm?', choices: ['a', 'b'] }).ok && w2.call({ key: 'mq', merge: 'm2' }).code === 'bad-merge' })())
})

// ================================================================= Q46: --move-to "suggest", the resolve helper
await section(() => {
  const w = world()
  w.call({ key: 'tests', label: 'Tests' })
  w.call({ key: 'pend', label: 'Pending', under: 'tests' })
  w.call({ key: 'passed', label: 'Passed', under: 'tests' })
  w.call({ key: 't1', label: 'T1', under: 'pend' })
  const s = w.sess(), s0 = snap(s)
  const r1 = w.call({ key: 't1', text: '@passed', move_to: '../Passed/Sub' })
  check('Q46: ../A/B is refused bad-path WITH suggest = the absolute path it resolves to now ("/Tests/Passed/Sub"), nothing written', r1.code === 'bad-path' && r1.suggest === '/Tests/Passed/Sub' && snap(s) === s0, J(r1))
  const r2 = w.call({ key: 't1', move_to: '../../Elsewhere' })
  check('Q46: ../../X → suggest "/Elsewhere"', r2.code === 'bad-path' && r2.suggest === '/Elsewhere')
  const r3 = w.call({ key: 't1', move_to: '../../tests/passed' })
  check('Q46: ../../R/X (once allowed) → refused, suggest spelt as the board spells it ("/Tests/Passed")', r3.code === 'bad-path' && r3.suggest === '/Tests/Passed')
  const r4 = w.call({ key: 't1', move_to: 'Inner' })
  check('Q45 + Q46: a bare X → bad-path, suggest = one level DOWN from the parent ("/Tests/Pending/Inner")', r4.code === 'bad-path' && r4.suggest === '/Tests/Pending/Inner')
  check('Q46: "../.." (no destination) → bad-path without a suggest; going above the root → no suggest', (r => r.code === 'bad-path' && !('suggest' in r))(w.call({ key: 't1', move_to: '../..' })) && (r => r.code === 'bad-path' && !('suggest' in r))(w.call({ key: 'tests', move_to: '../../X' })))
  check('Q46: a retry with the suggested absolute path works', w.call({ key: 't1', move_to: r3.suggest }).ok && w.byPath('Tests/Passed/T1') !== null)
  check('Q46: ../X (one step) still works', w.call({ key: 't1', move_to: '../Pending' }).ok && w.byPath('Tests/Pending/T1') !== null)
  // resolve
  const s1 = snap(s)
  const v1 = M.resolveCall(w.st, BRIDGET, { key: 't1', resolve: '../Passed' })
  check('resolve: ../Passed from Tests/Pending/T1 → "/Tests/Passed", live, its id', v1.ok && v1.path === '/Tests/Passed' && v1.state === 'live' && v1.id === w.get('passed').id && v1.from.key === 't1' && J(v1.create) === '[]', J(v1))
  const v2 = M.resolveCall(w.st, BRIDGET, { key: 't1', resolve: '../../R/X' })
  check('resolve: a deeper relative path too ("/R/X"), state new, id null, what a move would create', v2.ok && v2.path === '/R/X' && v2.state === 'new' && v2.id === null && J(v2.create) === J(['R', 'X']))
  check('resolve: a bare X (one level down from the parent) and an absolute path', M.resolveCall(w.st, BRIDGET, { key: 't1', resolve: 'Inner' }).path === '/Tests/Pending/Inner' && M.resolveCall(w.st, BRIDGET, { resolve: '/tests' }).id === w.get('tests').id)
  check('resolve: from the session root a relative path → bad-path (no parent); an unknown key → unknown-node', M.resolveCall(w.st, BRIDGET, { resolve: '../X' }).code === 'bad-path' && M.resolveCall(w.st, BRIDGET, { key: 'nokey', resolve: '../X' }).code === 'unknown-node')
  w.call({ key: 'gone', label: 'Gone bucket', under: 'tests', transient: true })
  w.call({ key: 'g1', label: 'G1', under: 'gone' })
  w.call({ key: 'g1', move_to: '../Pending' })
  const v3 = M.resolveCall(w.st, BRIDGET, { key: 'g1', resolve: '../Gone bucket' })
  check('resolve: a same-label GHOST is found (state ghost, its id: a move there would resurrect it)', v3.ok && v3.state === 'ghost' && v3.id === s.scope.get(s.rootId + '\ngone') && v3.path === '/Tests/Gone bucket', J(v3))
  check('resolve: CHANGES NOTHING (the tree, the scope, the aliases)', (() => { const before = snap(s); M.resolveCall(w.st, BRIDGET, { key: 't1', resolve: '../X/Y' }); M.resolveCall(w.st, BRIDGET, { path: 'Tests/Pending', resolve: '../Passed' }); return snap(s) === before })() && s1 !== null)
  check('resolve: takes only agent, key | id | path and resolve', M.resolveCall(w.st, BRIDGET, { resolve: '/x', text: 'hi' }).code === 'bad-input')
})

console.log(`\n${pass} passed, ${fail} failed`)
process.exit(fail ? 1 : 0)
